GET http://localhost:3000/api/organizations/123

###
POST http://localhost:3000/api/organizations
Content-Type: application/json

{
    "id": "123",
    "name": "Test Organization"
}


###
GET http://localhost:3000/api/organizations/123/deployments/0Afak00000X387hCAB

###
POST http://localhost:3000/api/organizations/123/deployments
Content-Type: application/json

< fixtures/success-deploy-response.json