
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Organization
 * 
 */
export type Organization = Prisma.OrganizationModel
/**
 * Model ApiKey
 * 
 */
export type ApiKey = Prisma.ApiKeyModel
/**
 * Model Deployment
 * 
 */
export type Deployment = Prisma.DeploymentModel
/**
 * Model DeployComponentSuccess
 * 
 */
export type DeployComponentSuccess = Prisma.DeployComponentSuccessModel
/**
 * Model DeployComponentFailure
 * 
 */
export type DeployComponentFailure = Prisma.DeployComponentFailureModel
/**
 * Model DeployTestSuccess
 * 
 */
export type DeployTestSuccess = Prisma.DeployTestSuccessModel
/**
 * Model DeployTestFailure
 * 
 */
export type DeployTestFailure = Prisma.DeployTestFailureModel
