
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DeployComponentSuccess` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DeployComponentSuccess
 * 
 */
export type DeployComponentSuccessModel = runtime.Types.Result.DefaultSelection<Prisma.$DeployComponentSuccessPayload>

export type AggregateDeployComponentSuccess = {
  _count: DeployComponentSuccessCountAggregateOutputType | null
  _min: DeployComponentSuccessMinAggregateOutputType | null
  _max: DeployComponentSuccessMaxAggregateOutputType | null
}

export type DeployComponentSuccessMinAggregateOutputType = {
  id: string | null
  fullName: string | null
  componentType: string | null
  changed: boolean | null
  created: boolean | null
  deleted: boolean | null
  deploymentId: string | null
}

export type DeployComponentSuccessMaxAggregateOutputType = {
  id: string | null
  fullName: string | null
  componentType: string | null
  changed: boolean | null
  created: boolean | null
  deleted: boolean | null
  deploymentId: string | null
}

export type DeployComponentSuccessCountAggregateOutputType = {
  id: number
  fullName: number
  componentType: number
  changed: number
  created: number
  deleted: number
  deploymentId: number
  _all: number
}


export type DeployComponentSuccessMinAggregateInputType = {
  id?: true
  fullName?: true
  componentType?: true
  changed?: true
  created?: true
  deleted?: true
  deploymentId?: true
}

export type DeployComponentSuccessMaxAggregateInputType = {
  id?: true
  fullName?: true
  componentType?: true
  changed?: true
  created?: true
  deleted?: true
  deploymentId?: true
}

export type DeployComponentSuccessCountAggregateInputType = {
  id?: true
  fullName?: true
  componentType?: true
  changed?: true
  created?: true
  deleted?: true
  deploymentId?: true
  _all?: true
}

export type DeployComponentSuccessAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DeployComponentSuccess to aggregate.
   */
  where?: Prisma.DeployComponentSuccessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DeployComponentSuccesses to fetch.
   */
  orderBy?: Prisma.DeployComponentSuccessOrderByWithRelationInput | Prisma.DeployComponentSuccessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DeployComponentSuccessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DeployComponentSuccesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DeployComponentSuccesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DeployComponentSuccesses
  **/
  _count?: true | DeployComponentSuccessCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DeployComponentSuccessMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DeployComponentSuccessMaxAggregateInputType
}

export type GetDeployComponentSuccessAggregateType<T extends DeployComponentSuccessAggregateArgs> = {
      [P in keyof T & keyof AggregateDeployComponentSuccess]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDeployComponentSuccess[P]>
    : Prisma.GetScalarType<T[P], AggregateDeployComponentSuccess[P]>
}




export type DeployComponentSuccessGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DeployComponentSuccessWhereInput
  orderBy?: Prisma.DeployComponentSuccessOrderByWithAggregationInput | Prisma.DeployComponentSuccessOrderByWithAggregationInput[]
  by: Prisma.DeployComponentSuccessScalarFieldEnum[] | Prisma.DeployComponentSuccessScalarFieldEnum
  having?: Prisma.DeployComponentSuccessScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DeployComponentSuccessCountAggregateInputType | true
  _min?: DeployComponentSuccessMinAggregateInputType
  _max?: DeployComponentSuccessMaxAggregateInputType
}

export type DeployComponentSuccessGroupByOutputType = {
  id: string
  fullName: string
  componentType: string
  changed: boolean
  created: boolean
  deleted: boolean
  deploymentId: string
  _count: DeployComponentSuccessCountAggregateOutputType | null
  _min: DeployComponentSuccessMinAggregateOutputType | null
  _max: DeployComponentSuccessMaxAggregateOutputType | null
}

export type GetDeployComponentSuccessGroupByPayload<T extends DeployComponentSuccessGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DeployComponentSuccessGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DeployComponentSuccessGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DeployComponentSuccessGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DeployComponentSuccessGroupByOutputType[P]>
      }
    >
  >



export type DeployComponentSuccessWhereInput = {
  AND?: Prisma.DeployComponentSuccessWhereInput | Prisma.DeployComponentSuccessWhereInput[]
  OR?: Prisma.DeployComponentSuccessWhereInput[]
  NOT?: Prisma.DeployComponentSuccessWhereInput | Prisma.DeployComponentSuccessWhereInput[]
  id?: Prisma.StringFilter<"DeployComponentSuccess"> | string
  fullName?: Prisma.StringFilter<"DeployComponentSuccess"> | string
  componentType?: Prisma.StringFilter<"DeployComponentSuccess"> | string
  changed?: Prisma.BoolFilter<"DeployComponentSuccess"> | boolean
  created?: Prisma.BoolFilter<"DeployComponentSuccess"> | boolean
  deleted?: Prisma.BoolFilter<"DeployComponentSuccess"> | boolean
  deploymentId?: Prisma.StringFilter<"DeployComponentSuccess"> | string
  Deployment?: Prisma.XOR<Prisma.DeploymentScalarRelationFilter, Prisma.DeploymentWhereInput>
}

export type DeployComponentSuccessOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  componentType?: Prisma.SortOrder
  changed?: Prisma.SortOrder
  created?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
  Deployment?: Prisma.DeploymentOrderByWithRelationInput
}

export type DeployComponentSuccessWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DeployComponentSuccessWhereInput | Prisma.DeployComponentSuccessWhereInput[]
  OR?: Prisma.DeployComponentSuccessWhereInput[]
  NOT?: Prisma.DeployComponentSuccessWhereInput | Prisma.DeployComponentSuccessWhereInput[]
  fullName?: Prisma.StringFilter<"DeployComponentSuccess"> | string
  componentType?: Prisma.StringFilter<"DeployComponentSuccess"> | string
  changed?: Prisma.BoolFilter<"DeployComponentSuccess"> | boolean
  created?: Prisma.BoolFilter<"DeployComponentSuccess"> | boolean
  deleted?: Prisma.BoolFilter<"DeployComponentSuccess"> | boolean
  deploymentId?: Prisma.StringFilter<"DeployComponentSuccess"> | string
  Deployment?: Prisma.XOR<Prisma.DeploymentScalarRelationFilter, Prisma.DeploymentWhereInput>
}, "id">

export type DeployComponentSuccessOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  componentType?: Prisma.SortOrder
  changed?: Prisma.SortOrder
  created?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
  _count?: Prisma.DeployComponentSuccessCountOrderByAggregateInput
  _max?: Prisma.DeployComponentSuccessMaxOrderByAggregateInput
  _min?: Prisma.DeployComponentSuccessMinOrderByAggregateInput
}

export type DeployComponentSuccessScalarWhereWithAggregatesInput = {
  AND?: Prisma.DeployComponentSuccessScalarWhereWithAggregatesInput | Prisma.DeployComponentSuccessScalarWhereWithAggregatesInput[]
  OR?: Prisma.DeployComponentSuccessScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DeployComponentSuccessScalarWhereWithAggregatesInput | Prisma.DeployComponentSuccessScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DeployComponentSuccess"> | string
  fullName?: Prisma.StringWithAggregatesFilter<"DeployComponentSuccess"> | string
  componentType?: Prisma.StringWithAggregatesFilter<"DeployComponentSuccess"> | string
  changed?: Prisma.BoolWithAggregatesFilter<"DeployComponentSuccess"> | boolean
  created?: Prisma.BoolWithAggregatesFilter<"DeployComponentSuccess"> | boolean
  deleted?: Prisma.BoolWithAggregatesFilter<"DeployComponentSuccess"> | boolean
  deploymentId?: Prisma.StringWithAggregatesFilter<"DeployComponentSuccess"> | string
}

export type DeployComponentSuccessCreateInput = {
  id?: string
  fullName: string
  componentType: string
  changed: boolean
  created: boolean
  deleted: boolean
  Deployment: Prisma.DeploymentCreateNestedOneWithoutComponentSuccessesInput
}

export type DeployComponentSuccessUncheckedCreateInput = {
  id?: string
  fullName: string
  componentType: string
  changed: boolean
  created: boolean
  deleted: boolean
  deploymentId: string
}

export type DeployComponentSuccessUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  componentType?: Prisma.StringFieldUpdateOperationsInput | string
  changed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Deployment?: Prisma.DeploymentUpdateOneRequiredWithoutComponentSuccessesNestedInput
}

export type DeployComponentSuccessUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  componentType?: Prisma.StringFieldUpdateOperationsInput | string
  changed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deploymentId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DeployComponentSuccessCreateManyInput = {
  id?: string
  fullName: string
  componentType: string
  changed: boolean
  created: boolean
  deleted: boolean
  deploymentId: string
}

export type DeployComponentSuccessUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  componentType?: Prisma.StringFieldUpdateOperationsInput | string
  changed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type DeployComponentSuccessUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  componentType?: Prisma.StringFieldUpdateOperationsInput | string
  changed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deploymentId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DeployComponentSuccessListRelationFilter = {
  every?: Prisma.DeployComponentSuccessWhereInput
  some?: Prisma.DeployComponentSuccessWhereInput
  none?: Prisma.DeployComponentSuccessWhereInput
}

export type DeployComponentSuccessOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DeployComponentSuccessCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  componentType?: Prisma.SortOrder
  changed?: Prisma.SortOrder
  created?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
}

export type DeployComponentSuccessMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  componentType?: Prisma.SortOrder
  changed?: Prisma.SortOrder
  created?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
}

export type DeployComponentSuccessMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  componentType?: Prisma.SortOrder
  changed?: Prisma.SortOrder
  created?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
}

export type DeployComponentSuccessCreateNestedManyWithoutDeploymentInput = {
  create?: Prisma.XOR<Prisma.DeployComponentSuccessCreateWithoutDeploymentInput, Prisma.DeployComponentSuccessUncheckedCreateWithoutDeploymentInput> | Prisma.DeployComponentSuccessCreateWithoutDeploymentInput[] | Prisma.DeployComponentSuccessUncheckedCreateWithoutDeploymentInput[]
  connectOrCreate?: Prisma.DeployComponentSuccessCreateOrConnectWithoutDeploymentInput | Prisma.DeployComponentSuccessCreateOrConnectWithoutDeploymentInput[]
  createMany?: Prisma.DeployComponentSuccessCreateManyDeploymentInputEnvelope
  connect?: Prisma.DeployComponentSuccessWhereUniqueInput | Prisma.DeployComponentSuccessWhereUniqueInput[]
}

export type DeployComponentSuccessUncheckedCreateNestedManyWithoutDeploymentInput = {
  create?: Prisma.XOR<Prisma.DeployComponentSuccessCreateWithoutDeploymentInput, Prisma.DeployComponentSuccessUncheckedCreateWithoutDeploymentInput> | Prisma.DeployComponentSuccessCreateWithoutDeploymentInput[] | Prisma.DeployComponentSuccessUncheckedCreateWithoutDeploymentInput[]
  connectOrCreate?: Prisma.DeployComponentSuccessCreateOrConnectWithoutDeploymentInput | Prisma.DeployComponentSuccessCreateOrConnectWithoutDeploymentInput[]
  createMany?: Prisma.DeployComponentSuccessCreateManyDeploymentInputEnvelope
  connect?: Prisma.DeployComponentSuccessWhereUniqueInput | Prisma.DeployComponentSuccessWhereUniqueInput[]
}

export type DeployComponentSuccessUpdateManyWithoutDeploymentNestedInput = {
  create?: Prisma.XOR<Prisma.DeployComponentSuccessCreateWithoutDeploymentInput, Prisma.DeployComponentSuccessUncheckedCreateWithoutDeploymentInput> | Prisma.DeployComponentSuccessCreateWithoutDeploymentInput[] | Prisma.DeployComponentSuccessUncheckedCreateWithoutDeploymentInput[]
  connectOrCreate?: Prisma.DeployComponentSuccessCreateOrConnectWithoutDeploymentInput | Prisma.DeployComponentSuccessCreateOrConnectWithoutDeploymentInput[]
  upsert?: Prisma.DeployComponentSuccessUpsertWithWhereUniqueWithoutDeploymentInput | Prisma.DeployComponentSuccessUpsertWithWhereUniqueWithoutDeploymentInput[]
  createMany?: Prisma.DeployComponentSuccessCreateManyDeploymentInputEnvelope
  set?: Prisma.DeployComponentSuccessWhereUniqueInput | Prisma.DeployComponentSuccessWhereUniqueInput[]
  disconnect?: Prisma.DeployComponentSuccessWhereUniqueInput | Prisma.DeployComponentSuccessWhereUniqueInput[]
  delete?: Prisma.DeployComponentSuccessWhereUniqueInput | Prisma.DeployComponentSuccessWhereUniqueInput[]
  connect?: Prisma.DeployComponentSuccessWhereUniqueInput | Prisma.DeployComponentSuccessWhereUniqueInput[]
  update?: Prisma.DeployComponentSuccessUpdateWithWhereUniqueWithoutDeploymentInput | Prisma.DeployComponentSuccessUpdateWithWhereUniqueWithoutDeploymentInput[]
  updateMany?: Prisma.DeployComponentSuccessUpdateManyWithWhereWithoutDeploymentInput | Prisma.DeployComponentSuccessUpdateManyWithWhereWithoutDeploymentInput[]
  deleteMany?: Prisma.DeployComponentSuccessScalarWhereInput | Prisma.DeployComponentSuccessScalarWhereInput[]
}

export type DeployComponentSuccessUncheckedUpdateManyWithoutDeploymentNestedInput = {
  create?: Prisma.XOR<Prisma.DeployComponentSuccessCreateWithoutDeploymentInput, Prisma.DeployComponentSuccessUncheckedCreateWithoutDeploymentInput> | Prisma.DeployComponentSuccessCreateWithoutDeploymentInput[] | Prisma.DeployComponentSuccessUncheckedCreateWithoutDeploymentInput[]
  connectOrCreate?: Prisma.DeployComponentSuccessCreateOrConnectWithoutDeploymentInput | Prisma.DeployComponentSuccessCreateOrConnectWithoutDeploymentInput[]
  upsert?: Prisma.DeployComponentSuccessUpsertWithWhereUniqueWithoutDeploymentInput | Prisma.DeployComponentSuccessUpsertWithWhereUniqueWithoutDeploymentInput[]
  createMany?: Prisma.DeployComponentSuccessCreateManyDeploymentInputEnvelope
  set?: Prisma.DeployComponentSuccessWhereUniqueInput | Prisma.DeployComponentSuccessWhereUniqueInput[]
  disconnect?: Prisma.DeployComponentSuccessWhereUniqueInput | Prisma.DeployComponentSuccessWhereUniqueInput[]
  delete?: Prisma.DeployComponentSuccessWhereUniqueInput | Prisma.DeployComponentSuccessWhereUniqueInput[]
  connect?: Prisma.DeployComponentSuccessWhereUniqueInput | Prisma.DeployComponentSuccessWhereUniqueInput[]
  update?: Prisma.DeployComponentSuccessUpdateWithWhereUniqueWithoutDeploymentInput | Prisma.DeployComponentSuccessUpdateWithWhereUniqueWithoutDeploymentInput[]
  updateMany?: Prisma.DeployComponentSuccessUpdateManyWithWhereWithoutDeploymentInput | Prisma.DeployComponentSuccessUpdateManyWithWhereWithoutDeploymentInput[]
  deleteMany?: Prisma.DeployComponentSuccessScalarWhereInput | Prisma.DeployComponentSuccessScalarWhereInput[]
}

export type DeployComponentSuccessCreateWithoutDeploymentInput = {
  id?: string
  fullName: string
  componentType: string
  changed: boolean
  created: boolean
  deleted: boolean
}

export type DeployComponentSuccessUncheckedCreateWithoutDeploymentInput = {
  id?: string
  fullName: string
  componentType: string
  changed: boolean
  created: boolean
  deleted: boolean
}

export type DeployComponentSuccessCreateOrConnectWithoutDeploymentInput = {
  where: Prisma.DeployComponentSuccessWhereUniqueInput
  create: Prisma.XOR<Prisma.DeployComponentSuccessCreateWithoutDeploymentInput, Prisma.DeployComponentSuccessUncheckedCreateWithoutDeploymentInput>
}

export type DeployComponentSuccessCreateManyDeploymentInputEnvelope = {
  data: Prisma.DeployComponentSuccessCreateManyDeploymentInput | Prisma.DeployComponentSuccessCreateManyDeploymentInput[]
  skipDuplicates?: boolean
}

export type DeployComponentSuccessUpsertWithWhereUniqueWithoutDeploymentInput = {
  where: Prisma.DeployComponentSuccessWhereUniqueInput
  update: Prisma.XOR<Prisma.DeployComponentSuccessUpdateWithoutDeploymentInput, Prisma.DeployComponentSuccessUncheckedUpdateWithoutDeploymentInput>
  create: Prisma.XOR<Prisma.DeployComponentSuccessCreateWithoutDeploymentInput, Prisma.DeployComponentSuccessUncheckedCreateWithoutDeploymentInput>
}

export type DeployComponentSuccessUpdateWithWhereUniqueWithoutDeploymentInput = {
  where: Prisma.DeployComponentSuccessWhereUniqueInput
  data: Prisma.XOR<Prisma.DeployComponentSuccessUpdateWithoutDeploymentInput, Prisma.DeployComponentSuccessUncheckedUpdateWithoutDeploymentInput>
}

export type DeployComponentSuccessUpdateManyWithWhereWithoutDeploymentInput = {
  where: Prisma.DeployComponentSuccessScalarWhereInput
  data: Prisma.XOR<Prisma.DeployComponentSuccessUpdateManyMutationInput, Prisma.DeployComponentSuccessUncheckedUpdateManyWithoutDeploymentInput>
}

export type DeployComponentSuccessScalarWhereInput = {
  AND?: Prisma.DeployComponentSuccessScalarWhereInput | Prisma.DeployComponentSuccessScalarWhereInput[]
  OR?: Prisma.DeployComponentSuccessScalarWhereInput[]
  NOT?: Prisma.DeployComponentSuccessScalarWhereInput | Prisma.DeployComponentSuccessScalarWhereInput[]
  id?: Prisma.StringFilter<"DeployComponentSuccess"> | string
  fullName?: Prisma.StringFilter<"DeployComponentSuccess"> | string
  componentType?: Prisma.StringFilter<"DeployComponentSuccess"> | string
  changed?: Prisma.BoolFilter<"DeployComponentSuccess"> | boolean
  created?: Prisma.BoolFilter<"DeployComponentSuccess"> | boolean
  deleted?: Prisma.BoolFilter<"DeployComponentSuccess"> | boolean
  deploymentId?: Prisma.StringFilter<"DeployComponentSuccess"> | string
}

export type DeployComponentSuccessCreateManyDeploymentInput = {
  id?: string
  fullName: string
  componentType: string
  changed: boolean
  created: boolean
  deleted: boolean
}

export type DeployComponentSuccessUpdateWithoutDeploymentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  componentType?: Prisma.StringFieldUpdateOperationsInput | string
  changed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type DeployComponentSuccessUncheckedUpdateWithoutDeploymentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  componentType?: Prisma.StringFieldUpdateOperationsInput | string
  changed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type DeployComponentSuccessUncheckedUpdateManyWithoutDeploymentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  componentType?: Prisma.StringFieldUpdateOperationsInput | string
  changed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type DeployComponentSuccessSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fullName?: boolean
  componentType?: boolean
  changed?: boolean
  created?: boolean
  deleted?: boolean
  deploymentId?: boolean
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["deployComponentSuccess"]>

export type DeployComponentSuccessSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fullName?: boolean
  componentType?: boolean
  changed?: boolean
  created?: boolean
  deleted?: boolean
  deploymentId?: boolean
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["deployComponentSuccess"]>

export type DeployComponentSuccessSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fullName?: boolean
  componentType?: boolean
  changed?: boolean
  created?: boolean
  deleted?: boolean
  deploymentId?: boolean
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["deployComponentSuccess"]>

export type DeployComponentSuccessSelectScalar = {
  id?: boolean
  fullName?: boolean
  componentType?: boolean
  changed?: boolean
  created?: boolean
  deleted?: boolean
  deploymentId?: boolean
}

export type DeployComponentSuccessOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fullName" | "componentType" | "changed" | "created" | "deleted" | "deploymentId", ExtArgs["result"]["deployComponentSuccess"]>
export type DeployComponentSuccessInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}
export type DeployComponentSuccessIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}
export type DeployComponentSuccessIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}

export type $DeployComponentSuccessPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DeployComponentSuccess"
  objects: {
    Deployment: Prisma.$DeploymentPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fullName: string
    componentType: string
    changed: boolean
    created: boolean
    deleted: boolean
    deploymentId: string
  }, ExtArgs["result"]["deployComponentSuccess"]>
  composites: {}
}

export type DeployComponentSuccessGetPayload<S extends boolean | null | undefined | DeployComponentSuccessDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DeployComponentSuccessPayload, S>

export type DeployComponentSuccessCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DeployComponentSuccessFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DeployComponentSuccessCountAggregateInputType | true
  }

export interface DeployComponentSuccessDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DeployComponentSuccess'], meta: { name: 'DeployComponentSuccess' } }
  /**
   * Find zero or one DeployComponentSuccess that matches the filter.
   * @param {DeployComponentSuccessFindUniqueArgs} args - Arguments to find a DeployComponentSuccess
   * @example
   * // Get one DeployComponentSuccess
   * const deployComponentSuccess = await prisma.deployComponentSuccess.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DeployComponentSuccessFindUniqueArgs>(args: Prisma.SelectSubset<T, DeployComponentSuccessFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DeployComponentSuccessClient<runtime.Types.Result.GetResult<Prisma.$DeployComponentSuccessPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DeployComponentSuccess that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DeployComponentSuccessFindUniqueOrThrowArgs} args - Arguments to find a DeployComponentSuccess
   * @example
   * // Get one DeployComponentSuccess
   * const deployComponentSuccess = await prisma.deployComponentSuccess.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DeployComponentSuccessFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DeployComponentSuccessFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DeployComponentSuccessClient<runtime.Types.Result.GetResult<Prisma.$DeployComponentSuccessPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DeployComponentSuccess that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployComponentSuccessFindFirstArgs} args - Arguments to find a DeployComponentSuccess
   * @example
   * // Get one DeployComponentSuccess
   * const deployComponentSuccess = await prisma.deployComponentSuccess.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DeployComponentSuccessFindFirstArgs>(args?: Prisma.SelectSubset<T, DeployComponentSuccessFindFirstArgs<ExtArgs>>): Prisma.Prisma__DeployComponentSuccessClient<runtime.Types.Result.GetResult<Prisma.$DeployComponentSuccessPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DeployComponentSuccess that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployComponentSuccessFindFirstOrThrowArgs} args - Arguments to find a DeployComponentSuccess
   * @example
   * // Get one DeployComponentSuccess
   * const deployComponentSuccess = await prisma.deployComponentSuccess.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DeployComponentSuccessFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DeployComponentSuccessFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DeployComponentSuccessClient<runtime.Types.Result.GetResult<Prisma.$DeployComponentSuccessPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DeployComponentSuccesses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployComponentSuccessFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DeployComponentSuccesses
   * const deployComponentSuccesses = await prisma.deployComponentSuccess.findMany()
   * 
   * // Get first 10 DeployComponentSuccesses
   * const deployComponentSuccesses = await prisma.deployComponentSuccess.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const deployComponentSuccessWithIdOnly = await prisma.deployComponentSuccess.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DeployComponentSuccessFindManyArgs>(args?: Prisma.SelectSubset<T, DeployComponentSuccessFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DeployComponentSuccessPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DeployComponentSuccess.
   * @param {DeployComponentSuccessCreateArgs} args - Arguments to create a DeployComponentSuccess.
   * @example
   * // Create one DeployComponentSuccess
   * const DeployComponentSuccess = await prisma.deployComponentSuccess.create({
   *   data: {
   *     // ... data to create a DeployComponentSuccess
   *   }
   * })
   * 
   */
  create<T extends DeployComponentSuccessCreateArgs>(args: Prisma.SelectSubset<T, DeployComponentSuccessCreateArgs<ExtArgs>>): Prisma.Prisma__DeployComponentSuccessClient<runtime.Types.Result.GetResult<Prisma.$DeployComponentSuccessPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DeployComponentSuccesses.
   * @param {DeployComponentSuccessCreateManyArgs} args - Arguments to create many DeployComponentSuccesses.
   * @example
   * // Create many DeployComponentSuccesses
   * const deployComponentSuccess = await prisma.deployComponentSuccess.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DeployComponentSuccessCreateManyArgs>(args?: Prisma.SelectSubset<T, DeployComponentSuccessCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DeployComponentSuccesses and returns the data saved in the database.
   * @param {DeployComponentSuccessCreateManyAndReturnArgs} args - Arguments to create many DeployComponentSuccesses.
   * @example
   * // Create many DeployComponentSuccesses
   * const deployComponentSuccess = await prisma.deployComponentSuccess.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DeployComponentSuccesses and only return the `id`
   * const deployComponentSuccessWithIdOnly = await prisma.deployComponentSuccess.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DeployComponentSuccessCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DeployComponentSuccessCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DeployComponentSuccessPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DeployComponentSuccess.
   * @param {DeployComponentSuccessDeleteArgs} args - Arguments to delete one DeployComponentSuccess.
   * @example
   * // Delete one DeployComponentSuccess
   * const DeployComponentSuccess = await prisma.deployComponentSuccess.delete({
   *   where: {
   *     // ... filter to delete one DeployComponentSuccess
   *   }
   * })
   * 
   */
  delete<T extends DeployComponentSuccessDeleteArgs>(args: Prisma.SelectSubset<T, DeployComponentSuccessDeleteArgs<ExtArgs>>): Prisma.Prisma__DeployComponentSuccessClient<runtime.Types.Result.GetResult<Prisma.$DeployComponentSuccessPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DeployComponentSuccess.
   * @param {DeployComponentSuccessUpdateArgs} args - Arguments to update one DeployComponentSuccess.
   * @example
   * // Update one DeployComponentSuccess
   * const deployComponentSuccess = await prisma.deployComponentSuccess.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DeployComponentSuccessUpdateArgs>(args: Prisma.SelectSubset<T, DeployComponentSuccessUpdateArgs<ExtArgs>>): Prisma.Prisma__DeployComponentSuccessClient<runtime.Types.Result.GetResult<Prisma.$DeployComponentSuccessPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DeployComponentSuccesses.
   * @param {DeployComponentSuccessDeleteManyArgs} args - Arguments to filter DeployComponentSuccesses to delete.
   * @example
   * // Delete a few DeployComponentSuccesses
   * const { count } = await prisma.deployComponentSuccess.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DeployComponentSuccessDeleteManyArgs>(args?: Prisma.SelectSubset<T, DeployComponentSuccessDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DeployComponentSuccesses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployComponentSuccessUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DeployComponentSuccesses
   * const deployComponentSuccess = await prisma.deployComponentSuccess.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DeployComponentSuccessUpdateManyArgs>(args: Prisma.SelectSubset<T, DeployComponentSuccessUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DeployComponentSuccesses and returns the data updated in the database.
   * @param {DeployComponentSuccessUpdateManyAndReturnArgs} args - Arguments to update many DeployComponentSuccesses.
   * @example
   * // Update many DeployComponentSuccesses
   * const deployComponentSuccess = await prisma.deployComponentSuccess.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DeployComponentSuccesses and only return the `id`
   * const deployComponentSuccessWithIdOnly = await prisma.deployComponentSuccess.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DeployComponentSuccessUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DeployComponentSuccessUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DeployComponentSuccessPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DeployComponentSuccess.
   * @param {DeployComponentSuccessUpsertArgs} args - Arguments to update or create a DeployComponentSuccess.
   * @example
   * // Update or create a DeployComponentSuccess
   * const deployComponentSuccess = await prisma.deployComponentSuccess.upsert({
   *   create: {
   *     // ... data to create a DeployComponentSuccess
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DeployComponentSuccess we want to update
   *   }
   * })
   */
  upsert<T extends DeployComponentSuccessUpsertArgs>(args: Prisma.SelectSubset<T, DeployComponentSuccessUpsertArgs<ExtArgs>>): Prisma.Prisma__DeployComponentSuccessClient<runtime.Types.Result.GetResult<Prisma.$DeployComponentSuccessPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DeployComponentSuccesses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployComponentSuccessCountArgs} args - Arguments to filter DeployComponentSuccesses to count.
   * @example
   * // Count the number of DeployComponentSuccesses
   * const count = await prisma.deployComponentSuccess.count({
   *   where: {
   *     // ... the filter for the DeployComponentSuccesses we want to count
   *   }
   * })
  **/
  count<T extends DeployComponentSuccessCountArgs>(
    args?: Prisma.Subset<T, DeployComponentSuccessCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DeployComponentSuccessCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DeployComponentSuccess.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployComponentSuccessAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DeployComponentSuccessAggregateArgs>(args: Prisma.Subset<T, DeployComponentSuccessAggregateArgs>): Prisma.PrismaPromise<GetDeployComponentSuccessAggregateType<T>>

  /**
   * Group by DeployComponentSuccess.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployComponentSuccessGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DeployComponentSuccessGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DeployComponentSuccessGroupByArgs['orderBy'] }
      : { orderBy?: DeployComponentSuccessGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DeployComponentSuccessGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDeployComponentSuccessGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DeployComponentSuccess model
 */
readonly fields: DeployComponentSuccessFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DeployComponentSuccess.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DeployComponentSuccessClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Deployment<T extends Prisma.DeploymentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DeploymentDefaultArgs<ExtArgs>>): Prisma.Prisma__DeploymentClient<runtime.Types.Result.GetResult<Prisma.$DeploymentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DeployComponentSuccess model
 */
export interface DeployComponentSuccessFieldRefs {
  readonly id: Prisma.FieldRef<"DeployComponentSuccess", 'String'>
  readonly fullName: Prisma.FieldRef<"DeployComponentSuccess", 'String'>
  readonly componentType: Prisma.FieldRef<"DeployComponentSuccess", 'String'>
  readonly changed: Prisma.FieldRef<"DeployComponentSuccess", 'Boolean'>
  readonly created: Prisma.FieldRef<"DeployComponentSuccess", 'Boolean'>
  readonly deleted: Prisma.FieldRef<"DeployComponentSuccess", 'Boolean'>
  readonly deploymentId: Prisma.FieldRef<"DeployComponentSuccess", 'String'>
}
    

// Custom InputTypes
/**
 * DeployComponentSuccess findUnique
 */
export type DeployComponentSuccessFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentSuccess
   */
  select?: Prisma.DeployComponentSuccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentSuccess
   */
  omit?: Prisma.DeployComponentSuccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentSuccessInclude<ExtArgs> | null
  /**
   * Filter, which DeployComponentSuccess to fetch.
   */
  where: Prisma.DeployComponentSuccessWhereUniqueInput
}

/**
 * DeployComponentSuccess findUniqueOrThrow
 */
export type DeployComponentSuccessFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentSuccess
   */
  select?: Prisma.DeployComponentSuccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentSuccess
   */
  omit?: Prisma.DeployComponentSuccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentSuccessInclude<ExtArgs> | null
  /**
   * Filter, which DeployComponentSuccess to fetch.
   */
  where: Prisma.DeployComponentSuccessWhereUniqueInput
}

/**
 * DeployComponentSuccess findFirst
 */
export type DeployComponentSuccessFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentSuccess
   */
  select?: Prisma.DeployComponentSuccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentSuccess
   */
  omit?: Prisma.DeployComponentSuccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentSuccessInclude<ExtArgs> | null
  /**
   * Filter, which DeployComponentSuccess to fetch.
   */
  where?: Prisma.DeployComponentSuccessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DeployComponentSuccesses to fetch.
   */
  orderBy?: Prisma.DeployComponentSuccessOrderByWithRelationInput | Prisma.DeployComponentSuccessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DeployComponentSuccesses.
   */
  cursor?: Prisma.DeployComponentSuccessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DeployComponentSuccesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DeployComponentSuccesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DeployComponentSuccesses.
   */
  distinct?: Prisma.DeployComponentSuccessScalarFieldEnum | Prisma.DeployComponentSuccessScalarFieldEnum[]
}

/**
 * DeployComponentSuccess findFirstOrThrow
 */
export type DeployComponentSuccessFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentSuccess
   */
  select?: Prisma.DeployComponentSuccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentSuccess
   */
  omit?: Prisma.DeployComponentSuccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentSuccessInclude<ExtArgs> | null
  /**
   * Filter, which DeployComponentSuccess to fetch.
   */
  where?: Prisma.DeployComponentSuccessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DeployComponentSuccesses to fetch.
   */
  orderBy?: Prisma.DeployComponentSuccessOrderByWithRelationInput | Prisma.DeployComponentSuccessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DeployComponentSuccesses.
   */
  cursor?: Prisma.DeployComponentSuccessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DeployComponentSuccesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DeployComponentSuccesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DeployComponentSuccesses.
   */
  distinct?: Prisma.DeployComponentSuccessScalarFieldEnum | Prisma.DeployComponentSuccessScalarFieldEnum[]
}

/**
 * DeployComponentSuccess findMany
 */
export type DeployComponentSuccessFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentSuccess
   */
  select?: Prisma.DeployComponentSuccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentSuccess
   */
  omit?: Prisma.DeployComponentSuccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentSuccessInclude<ExtArgs> | null
  /**
   * Filter, which DeployComponentSuccesses to fetch.
   */
  where?: Prisma.DeployComponentSuccessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DeployComponentSuccesses to fetch.
   */
  orderBy?: Prisma.DeployComponentSuccessOrderByWithRelationInput | Prisma.DeployComponentSuccessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DeployComponentSuccesses.
   */
  cursor?: Prisma.DeployComponentSuccessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DeployComponentSuccesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DeployComponentSuccesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DeployComponentSuccesses.
   */
  distinct?: Prisma.DeployComponentSuccessScalarFieldEnum | Prisma.DeployComponentSuccessScalarFieldEnum[]
}

/**
 * DeployComponentSuccess create
 */
export type DeployComponentSuccessCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentSuccess
   */
  select?: Prisma.DeployComponentSuccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentSuccess
   */
  omit?: Prisma.DeployComponentSuccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentSuccessInclude<ExtArgs> | null
  /**
   * The data needed to create a DeployComponentSuccess.
   */
  data: Prisma.XOR<Prisma.DeployComponentSuccessCreateInput, Prisma.DeployComponentSuccessUncheckedCreateInput>
}

/**
 * DeployComponentSuccess createMany
 */
export type DeployComponentSuccessCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DeployComponentSuccesses.
   */
  data: Prisma.DeployComponentSuccessCreateManyInput | Prisma.DeployComponentSuccessCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DeployComponentSuccess createManyAndReturn
 */
export type DeployComponentSuccessCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentSuccess
   */
  select?: Prisma.DeployComponentSuccessSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentSuccess
   */
  omit?: Prisma.DeployComponentSuccessOmit<ExtArgs> | null
  /**
   * The data used to create many DeployComponentSuccesses.
   */
  data: Prisma.DeployComponentSuccessCreateManyInput | Prisma.DeployComponentSuccessCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentSuccessIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DeployComponentSuccess update
 */
export type DeployComponentSuccessUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentSuccess
   */
  select?: Prisma.DeployComponentSuccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentSuccess
   */
  omit?: Prisma.DeployComponentSuccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentSuccessInclude<ExtArgs> | null
  /**
   * The data needed to update a DeployComponentSuccess.
   */
  data: Prisma.XOR<Prisma.DeployComponentSuccessUpdateInput, Prisma.DeployComponentSuccessUncheckedUpdateInput>
  /**
   * Choose, which DeployComponentSuccess to update.
   */
  where: Prisma.DeployComponentSuccessWhereUniqueInput
}

/**
 * DeployComponentSuccess updateMany
 */
export type DeployComponentSuccessUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DeployComponentSuccesses.
   */
  data: Prisma.XOR<Prisma.DeployComponentSuccessUpdateManyMutationInput, Prisma.DeployComponentSuccessUncheckedUpdateManyInput>
  /**
   * Filter which DeployComponentSuccesses to update
   */
  where?: Prisma.DeployComponentSuccessWhereInput
  /**
   * Limit how many DeployComponentSuccesses to update.
   */
  limit?: number
}

/**
 * DeployComponentSuccess updateManyAndReturn
 */
export type DeployComponentSuccessUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentSuccess
   */
  select?: Prisma.DeployComponentSuccessSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentSuccess
   */
  omit?: Prisma.DeployComponentSuccessOmit<ExtArgs> | null
  /**
   * The data used to update DeployComponentSuccesses.
   */
  data: Prisma.XOR<Prisma.DeployComponentSuccessUpdateManyMutationInput, Prisma.DeployComponentSuccessUncheckedUpdateManyInput>
  /**
   * Filter which DeployComponentSuccesses to update
   */
  where?: Prisma.DeployComponentSuccessWhereInput
  /**
   * Limit how many DeployComponentSuccesses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentSuccessIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DeployComponentSuccess upsert
 */
export type DeployComponentSuccessUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentSuccess
   */
  select?: Prisma.DeployComponentSuccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentSuccess
   */
  omit?: Prisma.DeployComponentSuccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentSuccessInclude<ExtArgs> | null
  /**
   * The filter to search for the DeployComponentSuccess to update in case it exists.
   */
  where: Prisma.DeployComponentSuccessWhereUniqueInput
  /**
   * In case the DeployComponentSuccess found by the `where` argument doesn't exist, create a new DeployComponentSuccess with this data.
   */
  create: Prisma.XOR<Prisma.DeployComponentSuccessCreateInput, Prisma.DeployComponentSuccessUncheckedCreateInput>
  /**
   * In case the DeployComponentSuccess was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DeployComponentSuccessUpdateInput, Prisma.DeployComponentSuccessUncheckedUpdateInput>
}

/**
 * DeployComponentSuccess delete
 */
export type DeployComponentSuccessDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentSuccess
   */
  select?: Prisma.DeployComponentSuccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentSuccess
   */
  omit?: Prisma.DeployComponentSuccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentSuccessInclude<ExtArgs> | null
  /**
   * Filter which DeployComponentSuccess to delete.
   */
  where: Prisma.DeployComponentSuccessWhereUniqueInput
}

/**
 * DeployComponentSuccess deleteMany
 */
export type DeployComponentSuccessDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DeployComponentSuccesses to delete
   */
  where?: Prisma.DeployComponentSuccessWhereInput
  /**
   * Limit how many DeployComponentSuccesses to delete.
   */
  limit?: number
}

/**
 * DeployComponentSuccess without action
 */
export type DeployComponentSuccessDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentSuccess
   */
  select?: Prisma.DeployComponentSuccessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentSuccess
   */
  omit?: Prisma.DeployComponentSuccessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentSuccessInclude<ExtArgs> | null
}
