
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DeployComponentFailure` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DeployComponentFailure
 * 
 */
export type DeployComponentFailureModel = runtime.Types.Result.DefaultSelection<Prisma.$DeployComponentFailurePayload>

export type AggregateDeployComponentFailure = {
  _count: DeployComponentFailureCountAggregateOutputType | null
  _avg: DeployComponentFailureAvgAggregateOutputType | null
  _sum: DeployComponentFailureSumAggregateOutputType | null
  _min: DeployComponentFailureMinAggregateOutputType | null
  _max: DeployComponentFailureMaxAggregateOutputType | null
}

export type DeployComponentFailureAvgAggregateOutputType = {
  columnNumber: number | null
  lineNumber: number | null
}

export type DeployComponentFailureSumAggregateOutputType = {
  columnNumber: number | null
  lineNumber: number | null
}

export type DeployComponentFailureMinAggregateOutputType = {
  id: string | null
  fullName: string | null
  componentType: string | null
  changed: boolean | null
  created: boolean | null
  deleted: boolean | null
  columnNumber: number | null
  lineNumber: number | null
  problem: string | null
  problemType: string | null
  deploymentId: string | null
}

export type DeployComponentFailureMaxAggregateOutputType = {
  id: string | null
  fullName: string | null
  componentType: string | null
  changed: boolean | null
  created: boolean | null
  deleted: boolean | null
  columnNumber: number | null
  lineNumber: number | null
  problem: string | null
  problemType: string | null
  deploymentId: string | null
}

export type DeployComponentFailureCountAggregateOutputType = {
  id: number
  fullName: number
  componentType: number
  changed: number
  created: number
  deleted: number
  columnNumber: number
  lineNumber: number
  problem: number
  problemType: number
  deploymentId: number
  _all: number
}


export type DeployComponentFailureAvgAggregateInputType = {
  columnNumber?: true
  lineNumber?: true
}

export type DeployComponentFailureSumAggregateInputType = {
  columnNumber?: true
  lineNumber?: true
}

export type DeployComponentFailureMinAggregateInputType = {
  id?: true
  fullName?: true
  componentType?: true
  changed?: true
  created?: true
  deleted?: true
  columnNumber?: true
  lineNumber?: true
  problem?: true
  problemType?: true
  deploymentId?: true
}

export type DeployComponentFailureMaxAggregateInputType = {
  id?: true
  fullName?: true
  componentType?: true
  changed?: true
  created?: true
  deleted?: true
  columnNumber?: true
  lineNumber?: true
  problem?: true
  problemType?: true
  deploymentId?: true
}

export type DeployComponentFailureCountAggregateInputType = {
  id?: true
  fullName?: true
  componentType?: true
  changed?: true
  created?: true
  deleted?: true
  columnNumber?: true
  lineNumber?: true
  problem?: true
  problemType?: true
  deploymentId?: true
  _all?: true
}

export type DeployComponentFailureAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DeployComponentFailure to aggregate.
   */
  where?: Prisma.DeployComponentFailureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DeployComponentFailures to fetch.
   */
  orderBy?: Prisma.DeployComponentFailureOrderByWithRelationInput | Prisma.DeployComponentFailureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DeployComponentFailureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DeployComponentFailures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DeployComponentFailures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DeployComponentFailures
  **/
  _count?: true | DeployComponentFailureCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DeployComponentFailureAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DeployComponentFailureSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DeployComponentFailureMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DeployComponentFailureMaxAggregateInputType
}

export type GetDeployComponentFailureAggregateType<T extends DeployComponentFailureAggregateArgs> = {
      [P in keyof T & keyof AggregateDeployComponentFailure]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDeployComponentFailure[P]>
    : Prisma.GetScalarType<T[P], AggregateDeployComponentFailure[P]>
}




export type DeployComponentFailureGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DeployComponentFailureWhereInput
  orderBy?: Prisma.DeployComponentFailureOrderByWithAggregationInput | Prisma.DeployComponentFailureOrderByWithAggregationInput[]
  by: Prisma.DeployComponentFailureScalarFieldEnum[] | Prisma.DeployComponentFailureScalarFieldEnum
  having?: Prisma.DeployComponentFailureScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DeployComponentFailureCountAggregateInputType | true
  _avg?: DeployComponentFailureAvgAggregateInputType
  _sum?: DeployComponentFailureSumAggregateInputType
  _min?: DeployComponentFailureMinAggregateInputType
  _max?: DeployComponentFailureMaxAggregateInputType
}

export type DeployComponentFailureGroupByOutputType = {
  id: string
  fullName: string
  componentType: string
  changed: boolean
  created: boolean
  deleted: boolean
  columnNumber: number
  lineNumber: number
  problem: string
  problemType: string
  deploymentId: string
  _count: DeployComponentFailureCountAggregateOutputType | null
  _avg: DeployComponentFailureAvgAggregateOutputType | null
  _sum: DeployComponentFailureSumAggregateOutputType | null
  _min: DeployComponentFailureMinAggregateOutputType | null
  _max: DeployComponentFailureMaxAggregateOutputType | null
}

export type GetDeployComponentFailureGroupByPayload<T extends DeployComponentFailureGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DeployComponentFailureGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DeployComponentFailureGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DeployComponentFailureGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DeployComponentFailureGroupByOutputType[P]>
      }
    >
  >



export type DeployComponentFailureWhereInput = {
  AND?: Prisma.DeployComponentFailureWhereInput | Prisma.DeployComponentFailureWhereInput[]
  OR?: Prisma.DeployComponentFailureWhereInput[]
  NOT?: Prisma.DeployComponentFailureWhereInput | Prisma.DeployComponentFailureWhereInput[]
  id?: Prisma.StringFilter<"DeployComponentFailure"> | string
  fullName?: Prisma.StringFilter<"DeployComponentFailure"> | string
  componentType?: Prisma.StringFilter<"DeployComponentFailure"> | string
  changed?: Prisma.BoolFilter<"DeployComponentFailure"> | boolean
  created?: Prisma.BoolFilter<"DeployComponentFailure"> | boolean
  deleted?: Prisma.BoolFilter<"DeployComponentFailure"> | boolean
  columnNumber?: Prisma.IntFilter<"DeployComponentFailure"> | number
  lineNumber?: Prisma.IntFilter<"DeployComponentFailure"> | number
  problem?: Prisma.StringFilter<"DeployComponentFailure"> | string
  problemType?: Prisma.StringFilter<"DeployComponentFailure"> | string
  deploymentId?: Prisma.StringFilter<"DeployComponentFailure"> | string
  Deployment?: Prisma.XOR<Prisma.DeploymentScalarRelationFilter, Prisma.DeploymentWhereInput>
}

export type DeployComponentFailureOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  componentType?: Prisma.SortOrder
  changed?: Prisma.SortOrder
  created?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  columnNumber?: Prisma.SortOrder
  lineNumber?: Prisma.SortOrder
  problem?: Prisma.SortOrder
  problemType?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
  Deployment?: Prisma.DeploymentOrderByWithRelationInput
}

export type DeployComponentFailureWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DeployComponentFailureWhereInput | Prisma.DeployComponentFailureWhereInput[]
  OR?: Prisma.DeployComponentFailureWhereInput[]
  NOT?: Prisma.DeployComponentFailureWhereInput | Prisma.DeployComponentFailureWhereInput[]
  fullName?: Prisma.StringFilter<"DeployComponentFailure"> | string
  componentType?: Prisma.StringFilter<"DeployComponentFailure"> | string
  changed?: Prisma.BoolFilter<"DeployComponentFailure"> | boolean
  created?: Prisma.BoolFilter<"DeployComponentFailure"> | boolean
  deleted?: Prisma.BoolFilter<"DeployComponentFailure"> | boolean
  columnNumber?: Prisma.IntFilter<"DeployComponentFailure"> | number
  lineNumber?: Prisma.IntFilter<"DeployComponentFailure"> | number
  problem?: Prisma.StringFilter<"DeployComponentFailure"> | string
  problemType?: Prisma.StringFilter<"DeployComponentFailure"> | string
  deploymentId?: Prisma.StringFilter<"DeployComponentFailure"> | string
  Deployment?: Prisma.XOR<Prisma.DeploymentScalarRelationFilter, Prisma.DeploymentWhereInput>
}, "id">

export type DeployComponentFailureOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  componentType?: Prisma.SortOrder
  changed?: Prisma.SortOrder
  created?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  columnNumber?: Prisma.SortOrder
  lineNumber?: Prisma.SortOrder
  problem?: Prisma.SortOrder
  problemType?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
  _count?: Prisma.DeployComponentFailureCountOrderByAggregateInput
  _avg?: Prisma.DeployComponentFailureAvgOrderByAggregateInput
  _max?: Prisma.DeployComponentFailureMaxOrderByAggregateInput
  _min?: Prisma.DeployComponentFailureMinOrderByAggregateInput
  _sum?: Prisma.DeployComponentFailureSumOrderByAggregateInput
}

export type DeployComponentFailureScalarWhereWithAggregatesInput = {
  AND?: Prisma.DeployComponentFailureScalarWhereWithAggregatesInput | Prisma.DeployComponentFailureScalarWhereWithAggregatesInput[]
  OR?: Prisma.DeployComponentFailureScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DeployComponentFailureScalarWhereWithAggregatesInput | Prisma.DeployComponentFailureScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DeployComponentFailure"> | string
  fullName?: Prisma.StringWithAggregatesFilter<"DeployComponentFailure"> | string
  componentType?: Prisma.StringWithAggregatesFilter<"DeployComponentFailure"> | string
  changed?: Prisma.BoolWithAggregatesFilter<"DeployComponentFailure"> | boolean
  created?: Prisma.BoolWithAggregatesFilter<"DeployComponentFailure"> | boolean
  deleted?: Prisma.BoolWithAggregatesFilter<"DeployComponentFailure"> | boolean
  columnNumber?: Prisma.IntWithAggregatesFilter<"DeployComponentFailure"> | number
  lineNumber?: Prisma.IntWithAggregatesFilter<"DeployComponentFailure"> | number
  problem?: Prisma.StringWithAggregatesFilter<"DeployComponentFailure"> | string
  problemType?: Prisma.StringWithAggregatesFilter<"DeployComponentFailure"> | string
  deploymentId?: Prisma.StringWithAggregatesFilter<"DeployComponentFailure"> | string
}

export type DeployComponentFailureCreateInput = {
  id?: string
  fullName: string
  componentType: string
  changed: boolean
  created: boolean
  deleted: boolean
  columnNumber: number
  lineNumber: number
  problem: string
  problemType: string
  Deployment: Prisma.DeploymentCreateNestedOneWithoutComponentFailuresInput
}

export type DeployComponentFailureUncheckedCreateInput = {
  id?: string
  fullName: string
  componentType: string
  changed: boolean
  created: boolean
  deleted: boolean
  columnNumber: number
  lineNumber: number
  problem: string
  problemType: string
  deploymentId: string
}

export type DeployComponentFailureUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  componentType?: Prisma.StringFieldUpdateOperationsInput | string
  changed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  columnNumber?: Prisma.IntFieldUpdateOperationsInput | number
  lineNumber?: Prisma.IntFieldUpdateOperationsInput | number
  problem?: Prisma.StringFieldUpdateOperationsInput | string
  problemType?: Prisma.StringFieldUpdateOperationsInput | string
  Deployment?: Prisma.DeploymentUpdateOneRequiredWithoutComponentFailuresNestedInput
}

export type DeployComponentFailureUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  componentType?: Prisma.StringFieldUpdateOperationsInput | string
  changed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  columnNumber?: Prisma.IntFieldUpdateOperationsInput | number
  lineNumber?: Prisma.IntFieldUpdateOperationsInput | number
  problem?: Prisma.StringFieldUpdateOperationsInput | string
  problemType?: Prisma.StringFieldUpdateOperationsInput | string
  deploymentId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DeployComponentFailureCreateManyInput = {
  id?: string
  fullName: string
  componentType: string
  changed: boolean
  created: boolean
  deleted: boolean
  columnNumber: number
  lineNumber: number
  problem: string
  problemType: string
  deploymentId: string
}

export type DeployComponentFailureUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  componentType?: Prisma.StringFieldUpdateOperationsInput | string
  changed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  columnNumber?: Prisma.IntFieldUpdateOperationsInput | number
  lineNumber?: Prisma.IntFieldUpdateOperationsInput | number
  problem?: Prisma.StringFieldUpdateOperationsInput | string
  problemType?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DeployComponentFailureUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  componentType?: Prisma.StringFieldUpdateOperationsInput | string
  changed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  columnNumber?: Prisma.IntFieldUpdateOperationsInput | number
  lineNumber?: Prisma.IntFieldUpdateOperationsInput | number
  problem?: Prisma.StringFieldUpdateOperationsInput | string
  problemType?: Prisma.StringFieldUpdateOperationsInput | string
  deploymentId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DeployComponentFailureListRelationFilter = {
  every?: Prisma.DeployComponentFailureWhereInput
  some?: Prisma.DeployComponentFailureWhereInput
  none?: Prisma.DeployComponentFailureWhereInput
}

export type DeployComponentFailureOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DeployComponentFailureCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  componentType?: Prisma.SortOrder
  changed?: Prisma.SortOrder
  created?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  columnNumber?: Prisma.SortOrder
  lineNumber?: Prisma.SortOrder
  problem?: Prisma.SortOrder
  problemType?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
}

export type DeployComponentFailureAvgOrderByAggregateInput = {
  columnNumber?: Prisma.SortOrder
  lineNumber?: Prisma.SortOrder
}

export type DeployComponentFailureMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  componentType?: Prisma.SortOrder
  changed?: Prisma.SortOrder
  created?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  columnNumber?: Prisma.SortOrder
  lineNumber?: Prisma.SortOrder
  problem?: Prisma.SortOrder
  problemType?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
}

export type DeployComponentFailureMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  componentType?: Prisma.SortOrder
  changed?: Prisma.SortOrder
  created?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  columnNumber?: Prisma.SortOrder
  lineNumber?: Prisma.SortOrder
  problem?: Prisma.SortOrder
  problemType?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
}

export type DeployComponentFailureSumOrderByAggregateInput = {
  columnNumber?: Prisma.SortOrder
  lineNumber?: Prisma.SortOrder
}

export type DeployComponentFailureCreateNestedManyWithoutDeploymentInput = {
  create?: Prisma.XOR<Prisma.DeployComponentFailureCreateWithoutDeploymentInput, Prisma.DeployComponentFailureUncheckedCreateWithoutDeploymentInput> | Prisma.DeployComponentFailureCreateWithoutDeploymentInput[] | Prisma.DeployComponentFailureUncheckedCreateWithoutDeploymentInput[]
  connectOrCreate?: Prisma.DeployComponentFailureCreateOrConnectWithoutDeploymentInput | Prisma.DeployComponentFailureCreateOrConnectWithoutDeploymentInput[]
  createMany?: Prisma.DeployComponentFailureCreateManyDeploymentInputEnvelope
  connect?: Prisma.DeployComponentFailureWhereUniqueInput | Prisma.DeployComponentFailureWhereUniqueInput[]
}

export type DeployComponentFailureUncheckedCreateNestedManyWithoutDeploymentInput = {
  create?: Prisma.XOR<Prisma.DeployComponentFailureCreateWithoutDeploymentInput, Prisma.DeployComponentFailureUncheckedCreateWithoutDeploymentInput> | Prisma.DeployComponentFailureCreateWithoutDeploymentInput[] | Prisma.DeployComponentFailureUncheckedCreateWithoutDeploymentInput[]
  connectOrCreate?: Prisma.DeployComponentFailureCreateOrConnectWithoutDeploymentInput | Prisma.DeployComponentFailureCreateOrConnectWithoutDeploymentInput[]
  createMany?: Prisma.DeployComponentFailureCreateManyDeploymentInputEnvelope
  connect?: Prisma.DeployComponentFailureWhereUniqueInput | Prisma.DeployComponentFailureWhereUniqueInput[]
}

export type DeployComponentFailureUpdateManyWithoutDeploymentNestedInput = {
  create?: Prisma.XOR<Prisma.DeployComponentFailureCreateWithoutDeploymentInput, Prisma.DeployComponentFailureUncheckedCreateWithoutDeploymentInput> | Prisma.DeployComponentFailureCreateWithoutDeploymentInput[] | Prisma.DeployComponentFailureUncheckedCreateWithoutDeploymentInput[]
  connectOrCreate?: Prisma.DeployComponentFailureCreateOrConnectWithoutDeploymentInput | Prisma.DeployComponentFailureCreateOrConnectWithoutDeploymentInput[]
  upsert?: Prisma.DeployComponentFailureUpsertWithWhereUniqueWithoutDeploymentInput | Prisma.DeployComponentFailureUpsertWithWhereUniqueWithoutDeploymentInput[]
  createMany?: Prisma.DeployComponentFailureCreateManyDeploymentInputEnvelope
  set?: Prisma.DeployComponentFailureWhereUniqueInput | Prisma.DeployComponentFailureWhereUniqueInput[]
  disconnect?: Prisma.DeployComponentFailureWhereUniqueInput | Prisma.DeployComponentFailureWhereUniqueInput[]
  delete?: Prisma.DeployComponentFailureWhereUniqueInput | Prisma.DeployComponentFailureWhereUniqueInput[]
  connect?: Prisma.DeployComponentFailureWhereUniqueInput | Prisma.DeployComponentFailureWhereUniqueInput[]
  update?: Prisma.DeployComponentFailureUpdateWithWhereUniqueWithoutDeploymentInput | Prisma.DeployComponentFailureUpdateWithWhereUniqueWithoutDeploymentInput[]
  updateMany?: Prisma.DeployComponentFailureUpdateManyWithWhereWithoutDeploymentInput | Prisma.DeployComponentFailureUpdateManyWithWhereWithoutDeploymentInput[]
  deleteMany?: Prisma.DeployComponentFailureScalarWhereInput | Prisma.DeployComponentFailureScalarWhereInput[]
}

export type DeployComponentFailureUncheckedUpdateManyWithoutDeploymentNestedInput = {
  create?: Prisma.XOR<Prisma.DeployComponentFailureCreateWithoutDeploymentInput, Prisma.DeployComponentFailureUncheckedCreateWithoutDeploymentInput> | Prisma.DeployComponentFailureCreateWithoutDeploymentInput[] | Prisma.DeployComponentFailureUncheckedCreateWithoutDeploymentInput[]
  connectOrCreate?: Prisma.DeployComponentFailureCreateOrConnectWithoutDeploymentInput | Prisma.DeployComponentFailureCreateOrConnectWithoutDeploymentInput[]
  upsert?: Prisma.DeployComponentFailureUpsertWithWhereUniqueWithoutDeploymentInput | Prisma.DeployComponentFailureUpsertWithWhereUniqueWithoutDeploymentInput[]
  createMany?: Prisma.DeployComponentFailureCreateManyDeploymentInputEnvelope
  set?: Prisma.DeployComponentFailureWhereUniqueInput | Prisma.DeployComponentFailureWhereUniqueInput[]
  disconnect?: Prisma.DeployComponentFailureWhereUniqueInput | Prisma.DeployComponentFailureWhereUniqueInput[]
  delete?: Prisma.DeployComponentFailureWhereUniqueInput | Prisma.DeployComponentFailureWhereUniqueInput[]
  connect?: Prisma.DeployComponentFailureWhereUniqueInput | Prisma.DeployComponentFailureWhereUniqueInput[]
  update?: Prisma.DeployComponentFailureUpdateWithWhereUniqueWithoutDeploymentInput | Prisma.DeployComponentFailureUpdateWithWhereUniqueWithoutDeploymentInput[]
  updateMany?: Prisma.DeployComponentFailureUpdateManyWithWhereWithoutDeploymentInput | Prisma.DeployComponentFailureUpdateManyWithWhereWithoutDeploymentInput[]
  deleteMany?: Prisma.DeployComponentFailureScalarWhereInput | Prisma.DeployComponentFailureScalarWhereInput[]
}

export type DeployComponentFailureCreateWithoutDeploymentInput = {
  id?: string
  fullName: string
  componentType: string
  changed: boolean
  created: boolean
  deleted: boolean
  columnNumber: number
  lineNumber: number
  problem: string
  problemType: string
}

export type DeployComponentFailureUncheckedCreateWithoutDeploymentInput = {
  id?: string
  fullName: string
  componentType: string
  changed: boolean
  created: boolean
  deleted: boolean
  columnNumber: number
  lineNumber: number
  problem: string
  problemType: string
}

export type DeployComponentFailureCreateOrConnectWithoutDeploymentInput = {
  where: Prisma.DeployComponentFailureWhereUniqueInput
  create: Prisma.XOR<Prisma.DeployComponentFailureCreateWithoutDeploymentInput, Prisma.DeployComponentFailureUncheckedCreateWithoutDeploymentInput>
}

export type DeployComponentFailureCreateManyDeploymentInputEnvelope = {
  data: Prisma.DeployComponentFailureCreateManyDeploymentInput | Prisma.DeployComponentFailureCreateManyDeploymentInput[]
  skipDuplicates?: boolean
}

export type DeployComponentFailureUpsertWithWhereUniqueWithoutDeploymentInput = {
  where: Prisma.DeployComponentFailureWhereUniqueInput
  update: Prisma.XOR<Prisma.DeployComponentFailureUpdateWithoutDeploymentInput, Prisma.DeployComponentFailureUncheckedUpdateWithoutDeploymentInput>
  create: Prisma.XOR<Prisma.DeployComponentFailureCreateWithoutDeploymentInput, Prisma.DeployComponentFailureUncheckedCreateWithoutDeploymentInput>
}

export type DeployComponentFailureUpdateWithWhereUniqueWithoutDeploymentInput = {
  where: Prisma.DeployComponentFailureWhereUniqueInput
  data: Prisma.XOR<Prisma.DeployComponentFailureUpdateWithoutDeploymentInput, Prisma.DeployComponentFailureUncheckedUpdateWithoutDeploymentInput>
}

export type DeployComponentFailureUpdateManyWithWhereWithoutDeploymentInput = {
  where: Prisma.DeployComponentFailureScalarWhereInput
  data: Prisma.XOR<Prisma.DeployComponentFailureUpdateManyMutationInput, Prisma.DeployComponentFailureUncheckedUpdateManyWithoutDeploymentInput>
}

export type DeployComponentFailureScalarWhereInput = {
  AND?: Prisma.DeployComponentFailureScalarWhereInput | Prisma.DeployComponentFailureScalarWhereInput[]
  OR?: Prisma.DeployComponentFailureScalarWhereInput[]
  NOT?: Prisma.DeployComponentFailureScalarWhereInput | Prisma.DeployComponentFailureScalarWhereInput[]
  id?: Prisma.StringFilter<"DeployComponentFailure"> | string
  fullName?: Prisma.StringFilter<"DeployComponentFailure"> | string
  componentType?: Prisma.StringFilter<"DeployComponentFailure"> | string
  changed?: Prisma.BoolFilter<"DeployComponentFailure"> | boolean
  created?: Prisma.BoolFilter<"DeployComponentFailure"> | boolean
  deleted?: Prisma.BoolFilter<"DeployComponentFailure"> | boolean
  columnNumber?: Prisma.IntFilter<"DeployComponentFailure"> | number
  lineNumber?: Prisma.IntFilter<"DeployComponentFailure"> | number
  problem?: Prisma.StringFilter<"DeployComponentFailure"> | string
  problemType?: Prisma.StringFilter<"DeployComponentFailure"> | string
  deploymentId?: Prisma.StringFilter<"DeployComponentFailure"> | string
}

export type DeployComponentFailureCreateManyDeploymentInput = {
  id?: string
  fullName: string
  componentType: string
  changed: boolean
  created: boolean
  deleted: boolean
  columnNumber: number
  lineNumber: number
  problem: string
  problemType: string
}

export type DeployComponentFailureUpdateWithoutDeploymentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  componentType?: Prisma.StringFieldUpdateOperationsInput | string
  changed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  columnNumber?: Prisma.IntFieldUpdateOperationsInput | number
  lineNumber?: Prisma.IntFieldUpdateOperationsInput | number
  problem?: Prisma.StringFieldUpdateOperationsInput | string
  problemType?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DeployComponentFailureUncheckedUpdateWithoutDeploymentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  componentType?: Prisma.StringFieldUpdateOperationsInput | string
  changed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  columnNumber?: Prisma.IntFieldUpdateOperationsInput | number
  lineNumber?: Prisma.IntFieldUpdateOperationsInput | number
  problem?: Prisma.StringFieldUpdateOperationsInput | string
  problemType?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DeployComponentFailureUncheckedUpdateManyWithoutDeploymentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  componentType?: Prisma.StringFieldUpdateOperationsInput | string
  changed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  columnNumber?: Prisma.IntFieldUpdateOperationsInput | number
  lineNumber?: Prisma.IntFieldUpdateOperationsInput | number
  problem?: Prisma.StringFieldUpdateOperationsInput | string
  problemType?: Prisma.StringFieldUpdateOperationsInput | string
}



export type DeployComponentFailureSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fullName?: boolean
  componentType?: boolean
  changed?: boolean
  created?: boolean
  deleted?: boolean
  columnNumber?: boolean
  lineNumber?: boolean
  problem?: boolean
  problemType?: boolean
  deploymentId?: boolean
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["deployComponentFailure"]>

export type DeployComponentFailureSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fullName?: boolean
  componentType?: boolean
  changed?: boolean
  created?: boolean
  deleted?: boolean
  columnNumber?: boolean
  lineNumber?: boolean
  problem?: boolean
  problemType?: boolean
  deploymentId?: boolean
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["deployComponentFailure"]>

export type DeployComponentFailureSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fullName?: boolean
  componentType?: boolean
  changed?: boolean
  created?: boolean
  deleted?: boolean
  columnNumber?: boolean
  lineNumber?: boolean
  problem?: boolean
  problemType?: boolean
  deploymentId?: boolean
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["deployComponentFailure"]>

export type DeployComponentFailureSelectScalar = {
  id?: boolean
  fullName?: boolean
  componentType?: boolean
  changed?: boolean
  created?: boolean
  deleted?: boolean
  columnNumber?: boolean
  lineNumber?: boolean
  problem?: boolean
  problemType?: boolean
  deploymentId?: boolean
}

export type DeployComponentFailureOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fullName" | "componentType" | "changed" | "created" | "deleted" | "columnNumber" | "lineNumber" | "problem" | "problemType" | "deploymentId", ExtArgs["result"]["deployComponentFailure"]>
export type DeployComponentFailureInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}
export type DeployComponentFailureIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}
export type DeployComponentFailureIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}

export type $DeployComponentFailurePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DeployComponentFailure"
  objects: {
    Deployment: Prisma.$DeploymentPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fullName: string
    componentType: string
    changed: boolean
    created: boolean
    deleted: boolean
    columnNumber: number
    lineNumber: number
    problem: string
    problemType: string
    deploymentId: string
  }, ExtArgs["result"]["deployComponentFailure"]>
  composites: {}
}

export type DeployComponentFailureGetPayload<S extends boolean | null | undefined | DeployComponentFailureDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DeployComponentFailurePayload, S>

export type DeployComponentFailureCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DeployComponentFailureFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DeployComponentFailureCountAggregateInputType | true
  }

export interface DeployComponentFailureDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DeployComponentFailure'], meta: { name: 'DeployComponentFailure' } }
  /**
   * Find zero or one DeployComponentFailure that matches the filter.
   * @param {DeployComponentFailureFindUniqueArgs} args - Arguments to find a DeployComponentFailure
   * @example
   * // Get one DeployComponentFailure
   * const deployComponentFailure = await prisma.deployComponentFailure.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DeployComponentFailureFindUniqueArgs>(args: Prisma.SelectSubset<T, DeployComponentFailureFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DeployComponentFailureClient<runtime.Types.Result.GetResult<Prisma.$DeployComponentFailurePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DeployComponentFailure that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DeployComponentFailureFindUniqueOrThrowArgs} args - Arguments to find a DeployComponentFailure
   * @example
   * // Get one DeployComponentFailure
   * const deployComponentFailure = await prisma.deployComponentFailure.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DeployComponentFailureFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DeployComponentFailureFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DeployComponentFailureClient<runtime.Types.Result.GetResult<Prisma.$DeployComponentFailurePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DeployComponentFailure that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployComponentFailureFindFirstArgs} args - Arguments to find a DeployComponentFailure
   * @example
   * // Get one DeployComponentFailure
   * const deployComponentFailure = await prisma.deployComponentFailure.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DeployComponentFailureFindFirstArgs>(args?: Prisma.SelectSubset<T, DeployComponentFailureFindFirstArgs<ExtArgs>>): Prisma.Prisma__DeployComponentFailureClient<runtime.Types.Result.GetResult<Prisma.$DeployComponentFailurePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DeployComponentFailure that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployComponentFailureFindFirstOrThrowArgs} args - Arguments to find a DeployComponentFailure
   * @example
   * // Get one DeployComponentFailure
   * const deployComponentFailure = await prisma.deployComponentFailure.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DeployComponentFailureFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DeployComponentFailureFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DeployComponentFailureClient<runtime.Types.Result.GetResult<Prisma.$DeployComponentFailurePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DeployComponentFailures that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployComponentFailureFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DeployComponentFailures
   * const deployComponentFailures = await prisma.deployComponentFailure.findMany()
   * 
   * // Get first 10 DeployComponentFailures
   * const deployComponentFailures = await prisma.deployComponentFailure.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const deployComponentFailureWithIdOnly = await prisma.deployComponentFailure.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DeployComponentFailureFindManyArgs>(args?: Prisma.SelectSubset<T, DeployComponentFailureFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DeployComponentFailurePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DeployComponentFailure.
   * @param {DeployComponentFailureCreateArgs} args - Arguments to create a DeployComponentFailure.
   * @example
   * // Create one DeployComponentFailure
   * const DeployComponentFailure = await prisma.deployComponentFailure.create({
   *   data: {
   *     // ... data to create a DeployComponentFailure
   *   }
   * })
   * 
   */
  create<T extends DeployComponentFailureCreateArgs>(args: Prisma.SelectSubset<T, DeployComponentFailureCreateArgs<ExtArgs>>): Prisma.Prisma__DeployComponentFailureClient<runtime.Types.Result.GetResult<Prisma.$DeployComponentFailurePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DeployComponentFailures.
   * @param {DeployComponentFailureCreateManyArgs} args - Arguments to create many DeployComponentFailures.
   * @example
   * // Create many DeployComponentFailures
   * const deployComponentFailure = await prisma.deployComponentFailure.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DeployComponentFailureCreateManyArgs>(args?: Prisma.SelectSubset<T, DeployComponentFailureCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DeployComponentFailures and returns the data saved in the database.
   * @param {DeployComponentFailureCreateManyAndReturnArgs} args - Arguments to create many DeployComponentFailures.
   * @example
   * // Create many DeployComponentFailures
   * const deployComponentFailure = await prisma.deployComponentFailure.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DeployComponentFailures and only return the `id`
   * const deployComponentFailureWithIdOnly = await prisma.deployComponentFailure.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DeployComponentFailureCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DeployComponentFailureCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DeployComponentFailurePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DeployComponentFailure.
   * @param {DeployComponentFailureDeleteArgs} args - Arguments to delete one DeployComponentFailure.
   * @example
   * // Delete one DeployComponentFailure
   * const DeployComponentFailure = await prisma.deployComponentFailure.delete({
   *   where: {
   *     // ... filter to delete one DeployComponentFailure
   *   }
   * })
   * 
   */
  delete<T extends DeployComponentFailureDeleteArgs>(args: Prisma.SelectSubset<T, DeployComponentFailureDeleteArgs<ExtArgs>>): Prisma.Prisma__DeployComponentFailureClient<runtime.Types.Result.GetResult<Prisma.$DeployComponentFailurePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DeployComponentFailure.
   * @param {DeployComponentFailureUpdateArgs} args - Arguments to update one DeployComponentFailure.
   * @example
   * // Update one DeployComponentFailure
   * const deployComponentFailure = await prisma.deployComponentFailure.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DeployComponentFailureUpdateArgs>(args: Prisma.SelectSubset<T, DeployComponentFailureUpdateArgs<ExtArgs>>): Prisma.Prisma__DeployComponentFailureClient<runtime.Types.Result.GetResult<Prisma.$DeployComponentFailurePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DeployComponentFailures.
   * @param {DeployComponentFailureDeleteManyArgs} args - Arguments to filter DeployComponentFailures to delete.
   * @example
   * // Delete a few DeployComponentFailures
   * const { count } = await prisma.deployComponentFailure.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DeployComponentFailureDeleteManyArgs>(args?: Prisma.SelectSubset<T, DeployComponentFailureDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DeployComponentFailures.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployComponentFailureUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DeployComponentFailures
   * const deployComponentFailure = await prisma.deployComponentFailure.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DeployComponentFailureUpdateManyArgs>(args: Prisma.SelectSubset<T, DeployComponentFailureUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DeployComponentFailures and returns the data updated in the database.
   * @param {DeployComponentFailureUpdateManyAndReturnArgs} args - Arguments to update many DeployComponentFailures.
   * @example
   * // Update many DeployComponentFailures
   * const deployComponentFailure = await prisma.deployComponentFailure.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DeployComponentFailures and only return the `id`
   * const deployComponentFailureWithIdOnly = await prisma.deployComponentFailure.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DeployComponentFailureUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DeployComponentFailureUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DeployComponentFailurePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DeployComponentFailure.
   * @param {DeployComponentFailureUpsertArgs} args - Arguments to update or create a DeployComponentFailure.
   * @example
   * // Update or create a DeployComponentFailure
   * const deployComponentFailure = await prisma.deployComponentFailure.upsert({
   *   create: {
   *     // ... data to create a DeployComponentFailure
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DeployComponentFailure we want to update
   *   }
   * })
   */
  upsert<T extends DeployComponentFailureUpsertArgs>(args: Prisma.SelectSubset<T, DeployComponentFailureUpsertArgs<ExtArgs>>): Prisma.Prisma__DeployComponentFailureClient<runtime.Types.Result.GetResult<Prisma.$DeployComponentFailurePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DeployComponentFailures.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployComponentFailureCountArgs} args - Arguments to filter DeployComponentFailures to count.
   * @example
   * // Count the number of DeployComponentFailures
   * const count = await prisma.deployComponentFailure.count({
   *   where: {
   *     // ... the filter for the DeployComponentFailures we want to count
   *   }
   * })
  **/
  count<T extends DeployComponentFailureCountArgs>(
    args?: Prisma.Subset<T, DeployComponentFailureCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DeployComponentFailureCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DeployComponentFailure.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployComponentFailureAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DeployComponentFailureAggregateArgs>(args: Prisma.Subset<T, DeployComponentFailureAggregateArgs>): Prisma.PrismaPromise<GetDeployComponentFailureAggregateType<T>>

  /**
   * Group by DeployComponentFailure.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployComponentFailureGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DeployComponentFailureGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DeployComponentFailureGroupByArgs['orderBy'] }
      : { orderBy?: DeployComponentFailureGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DeployComponentFailureGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDeployComponentFailureGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DeployComponentFailure model
 */
readonly fields: DeployComponentFailureFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DeployComponentFailure.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DeployComponentFailureClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Deployment<T extends Prisma.DeploymentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DeploymentDefaultArgs<ExtArgs>>): Prisma.Prisma__DeploymentClient<runtime.Types.Result.GetResult<Prisma.$DeploymentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DeployComponentFailure model
 */
export interface DeployComponentFailureFieldRefs {
  readonly id: Prisma.FieldRef<"DeployComponentFailure", 'String'>
  readonly fullName: Prisma.FieldRef<"DeployComponentFailure", 'String'>
  readonly componentType: Prisma.FieldRef<"DeployComponentFailure", 'String'>
  readonly changed: Prisma.FieldRef<"DeployComponentFailure", 'Boolean'>
  readonly created: Prisma.FieldRef<"DeployComponentFailure", 'Boolean'>
  readonly deleted: Prisma.FieldRef<"DeployComponentFailure", 'Boolean'>
  readonly columnNumber: Prisma.FieldRef<"DeployComponentFailure", 'Int'>
  readonly lineNumber: Prisma.FieldRef<"DeployComponentFailure", 'Int'>
  readonly problem: Prisma.FieldRef<"DeployComponentFailure", 'String'>
  readonly problemType: Prisma.FieldRef<"DeployComponentFailure", 'String'>
  readonly deploymentId: Prisma.FieldRef<"DeployComponentFailure", 'String'>
}
    

// Custom InputTypes
/**
 * DeployComponentFailure findUnique
 */
export type DeployComponentFailureFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentFailure
   */
  select?: Prisma.DeployComponentFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentFailure
   */
  omit?: Prisma.DeployComponentFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentFailureInclude<ExtArgs> | null
  /**
   * Filter, which DeployComponentFailure to fetch.
   */
  where: Prisma.DeployComponentFailureWhereUniqueInput
}

/**
 * DeployComponentFailure findUniqueOrThrow
 */
export type DeployComponentFailureFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentFailure
   */
  select?: Prisma.DeployComponentFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentFailure
   */
  omit?: Prisma.DeployComponentFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentFailureInclude<ExtArgs> | null
  /**
   * Filter, which DeployComponentFailure to fetch.
   */
  where: Prisma.DeployComponentFailureWhereUniqueInput
}

/**
 * DeployComponentFailure findFirst
 */
export type DeployComponentFailureFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentFailure
   */
  select?: Prisma.DeployComponentFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentFailure
   */
  omit?: Prisma.DeployComponentFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentFailureInclude<ExtArgs> | null
  /**
   * Filter, which DeployComponentFailure to fetch.
   */
  where?: Prisma.DeployComponentFailureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DeployComponentFailures to fetch.
   */
  orderBy?: Prisma.DeployComponentFailureOrderByWithRelationInput | Prisma.DeployComponentFailureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DeployComponentFailures.
   */
  cursor?: Prisma.DeployComponentFailureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DeployComponentFailures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DeployComponentFailures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DeployComponentFailures.
   */
  distinct?: Prisma.DeployComponentFailureScalarFieldEnum | Prisma.DeployComponentFailureScalarFieldEnum[]
}

/**
 * DeployComponentFailure findFirstOrThrow
 */
export type DeployComponentFailureFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentFailure
   */
  select?: Prisma.DeployComponentFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentFailure
   */
  omit?: Prisma.DeployComponentFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentFailureInclude<ExtArgs> | null
  /**
   * Filter, which DeployComponentFailure to fetch.
   */
  where?: Prisma.DeployComponentFailureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DeployComponentFailures to fetch.
   */
  orderBy?: Prisma.DeployComponentFailureOrderByWithRelationInput | Prisma.DeployComponentFailureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DeployComponentFailures.
   */
  cursor?: Prisma.DeployComponentFailureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DeployComponentFailures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DeployComponentFailures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DeployComponentFailures.
   */
  distinct?: Prisma.DeployComponentFailureScalarFieldEnum | Prisma.DeployComponentFailureScalarFieldEnum[]
}

/**
 * DeployComponentFailure findMany
 */
export type DeployComponentFailureFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentFailure
   */
  select?: Prisma.DeployComponentFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentFailure
   */
  omit?: Prisma.DeployComponentFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentFailureInclude<ExtArgs> | null
  /**
   * Filter, which DeployComponentFailures to fetch.
   */
  where?: Prisma.DeployComponentFailureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DeployComponentFailures to fetch.
   */
  orderBy?: Prisma.DeployComponentFailureOrderByWithRelationInput | Prisma.DeployComponentFailureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DeployComponentFailures.
   */
  cursor?: Prisma.DeployComponentFailureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DeployComponentFailures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DeployComponentFailures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DeployComponentFailures.
   */
  distinct?: Prisma.DeployComponentFailureScalarFieldEnum | Prisma.DeployComponentFailureScalarFieldEnum[]
}

/**
 * DeployComponentFailure create
 */
export type DeployComponentFailureCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentFailure
   */
  select?: Prisma.DeployComponentFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentFailure
   */
  omit?: Prisma.DeployComponentFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentFailureInclude<ExtArgs> | null
  /**
   * The data needed to create a DeployComponentFailure.
   */
  data: Prisma.XOR<Prisma.DeployComponentFailureCreateInput, Prisma.DeployComponentFailureUncheckedCreateInput>
}

/**
 * DeployComponentFailure createMany
 */
export type DeployComponentFailureCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DeployComponentFailures.
   */
  data: Prisma.DeployComponentFailureCreateManyInput | Prisma.DeployComponentFailureCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DeployComponentFailure createManyAndReturn
 */
export type DeployComponentFailureCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentFailure
   */
  select?: Prisma.DeployComponentFailureSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentFailure
   */
  omit?: Prisma.DeployComponentFailureOmit<ExtArgs> | null
  /**
   * The data used to create many DeployComponentFailures.
   */
  data: Prisma.DeployComponentFailureCreateManyInput | Prisma.DeployComponentFailureCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentFailureIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DeployComponentFailure update
 */
export type DeployComponentFailureUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentFailure
   */
  select?: Prisma.DeployComponentFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentFailure
   */
  omit?: Prisma.DeployComponentFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentFailureInclude<ExtArgs> | null
  /**
   * The data needed to update a DeployComponentFailure.
   */
  data: Prisma.XOR<Prisma.DeployComponentFailureUpdateInput, Prisma.DeployComponentFailureUncheckedUpdateInput>
  /**
   * Choose, which DeployComponentFailure to update.
   */
  where: Prisma.DeployComponentFailureWhereUniqueInput
}

/**
 * DeployComponentFailure updateMany
 */
export type DeployComponentFailureUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DeployComponentFailures.
   */
  data: Prisma.XOR<Prisma.DeployComponentFailureUpdateManyMutationInput, Prisma.DeployComponentFailureUncheckedUpdateManyInput>
  /**
   * Filter which DeployComponentFailures to update
   */
  where?: Prisma.DeployComponentFailureWhereInput
  /**
   * Limit how many DeployComponentFailures to update.
   */
  limit?: number
}

/**
 * DeployComponentFailure updateManyAndReturn
 */
export type DeployComponentFailureUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentFailure
   */
  select?: Prisma.DeployComponentFailureSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentFailure
   */
  omit?: Prisma.DeployComponentFailureOmit<ExtArgs> | null
  /**
   * The data used to update DeployComponentFailures.
   */
  data: Prisma.XOR<Prisma.DeployComponentFailureUpdateManyMutationInput, Prisma.DeployComponentFailureUncheckedUpdateManyInput>
  /**
   * Filter which DeployComponentFailures to update
   */
  where?: Prisma.DeployComponentFailureWhereInput
  /**
   * Limit how many DeployComponentFailures to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentFailureIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DeployComponentFailure upsert
 */
export type DeployComponentFailureUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentFailure
   */
  select?: Prisma.DeployComponentFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentFailure
   */
  omit?: Prisma.DeployComponentFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentFailureInclude<ExtArgs> | null
  /**
   * The filter to search for the DeployComponentFailure to update in case it exists.
   */
  where: Prisma.DeployComponentFailureWhereUniqueInput
  /**
   * In case the DeployComponentFailure found by the `where` argument doesn't exist, create a new DeployComponentFailure with this data.
   */
  create: Prisma.XOR<Prisma.DeployComponentFailureCreateInput, Prisma.DeployComponentFailureUncheckedCreateInput>
  /**
   * In case the DeployComponentFailure was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DeployComponentFailureUpdateInput, Prisma.DeployComponentFailureUncheckedUpdateInput>
}

/**
 * DeployComponentFailure delete
 */
export type DeployComponentFailureDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentFailure
   */
  select?: Prisma.DeployComponentFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentFailure
   */
  omit?: Prisma.DeployComponentFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentFailureInclude<ExtArgs> | null
  /**
   * Filter which DeployComponentFailure to delete.
   */
  where: Prisma.DeployComponentFailureWhereUniqueInput
}

/**
 * DeployComponentFailure deleteMany
 */
export type DeployComponentFailureDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DeployComponentFailures to delete
   */
  where?: Prisma.DeployComponentFailureWhereInput
  /**
   * Limit how many DeployComponentFailures to delete.
   */
  limit?: number
}

/**
 * DeployComponentFailure without action
 */
export type DeployComponentFailureDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployComponentFailure
   */
  select?: Prisma.DeployComponentFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployComponentFailure
   */
  omit?: Prisma.DeployComponentFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployComponentFailureInclude<ExtArgs> | null
}
