
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DeployTestFailure` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DeployTestFailure
 * 
 */
export type DeployTestFailureModel = runtime.Types.Result.DefaultSelection<Prisma.$DeployTestFailurePayload>

export type AggregateDeployTestFailure = {
  _count: DeployTestFailureCountAggregateOutputType | null
  _avg: DeployTestFailureAvgAggregateOutputType | null
  _sum: DeployTestFailureSumAggregateOutputType | null
  _min: DeployTestFailureMinAggregateOutputType | null
  _max: DeployTestFailureMaxAggregateOutputType | null
}

export type DeployTestFailureAvgAggregateOutputType = {
  time: number | null
}

export type DeployTestFailureSumAggregateOutputType = {
  time: number | null
}

export type DeployTestFailureMinAggregateOutputType = {
  id: string | null
  className: string | null
  methodName: string | null
  namespace: string | null
  message: string | null
  stackTrace: string | null
  time: number | null
  type: string | null
  deploymentId: string | null
}

export type DeployTestFailureMaxAggregateOutputType = {
  id: string | null
  className: string | null
  methodName: string | null
  namespace: string | null
  message: string | null
  stackTrace: string | null
  time: number | null
  type: string | null
  deploymentId: string | null
}

export type DeployTestFailureCountAggregateOutputType = {
  id: number
  className: number
  methodName: number
  namespace: number
  message: number
  stackTrace: number
  time: number
  type: number
  deploymentId: number
  _all: number
}


export type DeployTestFailureAvgAggregateInputType = {
  time?: true
}

export type DeployTestFailureSumAggregateInputType = {
  time?: true
}

export type DeployTestFailureMinAggregateInputType = {
  id?: true
  className?: true
  methodName?: true
  namespace?: true
  message?: true
  stackTrace?: true
  time?: true
  type?: true
  deploymentId?: true
}

export type DeployTestFailureMaxAggregateInputType = {
  id?: true
  className?: true
  methodName?: true
  namespace?: true
  message?: true
  stackTrace?: true
  time?: true
  type?: true
  deploymentId?: true
}

export type DeployTestFailureCountAggregateInputType = {
  id?: true
  className?: true
  methodName?: true
  namespace?: true
  message?: true
  stackTrace?: true
  time?: true
  type?: true
  deploymentId?: true
  _all?: true
}

export type DeployTestFailureAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DeployTestFailure to aggregate.
   */
  where?: Prisma.DeployTestFailureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DeployTestFailures to fetch.
   */
  orderBy?: Prisma.DeployTestFailureOrderByWithRelationInput | Prisma.DeployTestFailureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DeployTestFailureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DeployTestFailures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DeployTestFailures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DeployTestFailures
  **/
  _count?: true | DeployTestFailureCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DeployTestFailureAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DeployTestFailureSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DeployTestFailureMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DeployTestFailureMaxAggregateInputType
}

export type GetDeployTestFailureAggregateType<T extends DeployTestFailureAggregateArgs> = {
      [P in keyof T & keyof AggregateDeployTestFailure]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDeployTestFailure[P]>
    : Prisma.GetScalarType<T[P], AggregateDeployTestFailure[P]>
}




export type DeployTestFailureGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DeployTestFailureWhereInput
  orderBy?: Prisma.DeployTestFailureOrderByWithAggregationInput | Prisma.DeployTestFailureOrderByWithAggregationInput[]
  by: Prisma.DeployTestFailureScalarFieldEnum[] | Prisma.DeployTestFailureScalarFieldEnum
  having?: Prisma.DeployTestFailureScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DeployTestFailureCountAggregateInputType | true
  _avg?: DeployTestFailureAvgAggregateInputType
  _sum?: DeployTestFailureSumAggregateInputType
  _min?: DeployTestFailureMinAggregateInputType
  _max?: DeployTestFailureMaxAggregateInputType
}

export type DeployTestFailureGroupByOutputType = {
  id: string
  className: string
  methodName: string
  namespace: string | null
  message: string
  stackTrace: string
  time: number
  type: string
  deploymentId: string
  _count: DeployTestFailureCountAggregateOutputType | null
  _avg: DeployTestFailureAvgAggregateOutputType | null
  _sum: DeployTestFailureSumAggregateOutputType | null
  _min: DeployTestFailureMinAggregateOutputType | null
  _max: DeployTestFailureMaxAggregateOutputType | null
}

export type GetDeployTestFailureGroupByPayload<T extends DeployTestFailureGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DeployTestFailureGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DeployTestFailureGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DeployTestFailureGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DeployTestFailureGroupByOutputType[P]>
      }
    >
  >



export type DeployTestFailureWhereInput = {
  AND?: Prisma.DeployTestFailureWhereInput | Prisma.DeployTestFailureWhereInput[]
  OR?: Prisma.DeployTestFailureWhereInput[]
  NOT?: Prisma.DeployTestFailureWhereInput | Prisma.DeployTestFailureWhereInput[]
  id?: Prisma.StringFilter<"DeployTestFailure"> | string
  className?: Prisma.StringFilter<"DeployTestFailure"> | string
  methodName?: Prisma.StringFilter<"DeployTestFailure"> | string
  namespace?: Prisma.StringNullableFilter<"DeployTestFailure"> | string | null
  message?: Prisma.StringFilter<"DeployTestFailure"> | string
  stackTrace?: Prisma.StringFilter<"DeployTestFailure"> | string
  time?: Prisma.IntFilter<"DeployTestFailure"> | number
  type?: Prisma.StringFilter<"DeployTestFailure"> | string
  deploymentId?: Prisma.StringFilter<"DeployTestFailure"> | string
  Deployment?: Prisma.XOR<Prisma.DeploymentScalarRelationFilter, Prisma.DeploymentWhereInput>
}

export type DeployTestFailureOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  className?: Prisma.SortOrder
  methodName?: Prisma.SortOrder
  namespace?: Prisma.SortOrderInput | Prisma.SortOrder
  message?: Prisma.SortOrder
  stackTrace?: Prisma.SortOrder
  time?: Prisma.SortOrder
  type?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
  Deployment?: Prisma.DeploymentOrderByWithRelationInput
}

export type DeployTestFailureWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DeployTestFailureWhereInput | Prisma.DeployTestFailureWhereInput[]
  OR?: Prisma.DeployTestFailureWhereInput[]
  NOT?: Prisma.DeployTestFailureWhereInput | Prisma.DeployTestFailureWhereInput[]
  className?: Prisma.StringFilter<"DeployTestFailure"> | string
  methodName?: Prisma.StringFilter<"DeployTestFailure"> | string
  namespace?: Prisma.StringNullableFilter<"DeployTestFailure"> | string | null
  message?: Prisma.StringFilter<"DeployTestFailure"> | string
  stackTrace?: Prisma.StringFilter<"DeployTestFailure"> | string
  time?: Prisma.IntFilter<"DeployTestFailure"> | number
  type?: Prisma.StringFilter<"DeployTestFailure"> | string
  deploymentId?: Prisma.StringFilter<"DeployTestFailure"> | string
  Deployment?: Prisma.XOR<Prisma.DeploymentScalarRelationFilter, Prisma.DeploymentWhereInput>
}, "id">

export type DeployTestFailureOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  className?: Prisma.SortOrder
  methodName?: Prisma.SortOrder
  namespace?: Prisma.SortOrderInput | Prisma.SortOrder
  message?: Prisma.SortOrder
  stackTrace?: Prisma.SortOrder
  time?: Prisma.SortOrder
  type?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
  _count?: Prisma.DeployTestFailureCountOrderByAggregateInput
  _avg?: Prisma.DeployTestFailureAvgOrderByAggregateInput
  _max?: Prisma.DeployTestFailureMaxOrderByAggregateInput
  _min?: Prisma.DeployTestFailureMinOrderByAggregateInput
  _sum?: Prisma.DeployTestFailureSumOrderByAggregateInput
}

export type DeployTestFailureScalarWhereWithAggregatesInput = {
  AND?: Prisma.DeployTestFailureScalarWhereWithAggregatesInput | Prisma.DeployTestFailureScalarWhereWithAggregatesInput[]
  OR?: Prisma.DeployTestFailureScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DeployTestFailureScalarWhereWithAggregatesInput | Prisma.DeployTestFailureScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DeployTestFailure"> | string
  className?: Prisma.StringWithAggregatesFilter<"DeployTestFailure"> | string
  methodName?: Prisma.StringWithAggregatesFilter<"DeployTestFailure"> | string
  namespace?: Prisma.StringNullableWithAggregatesFilter<"DeployTestFailure"> | string | null
  message?: Prisma.StringWithAggregatesFilter<"DeployTestFailure"> | string
  stackTrace?: Prisma.StringWithAggregatesFilter<"DeployTestFailure"> | string
  time?: Prisma.IntWithAggregatesFilter<"DeployTestFailure"> | number
  type?: Prisma.StringWithAggregatesFilter<"DeployTestFailure"> | string
  deploymentId?: Prisma.StringWithAggregatesFilter<"DeployTestFailure"> | string
}

export type DeployTestFailureCreateInput = {
  id?: string
  className: string
  methodName: string
  namespace?: string | null
  message: string
  stackTrace: string
  time: number
  type: string
  Deployment: Prisma.DeploymentCreateNestedOneWithoutTestFailuresInput
}

export type DeployTestFailureUncheckedCreateInput = {
  id?: string
  className: string
  methodName: string
  namespace?: string | null
  message: string
  stackTrace: string
  time: number
  type: string
  deploymentId: string
}

export type DeployTestFailureUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  className?: Prisma.StringFieldUpdateOperationsInput | string
  methodName?: Prisma.StringFieldUpdateOperationsInput | string
  namespace?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  stackTrace?: Prisma.StringFieldUpdateOperationsInput | string
  time?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  Deployment?: Prisma.DeploymentUpdateOneRequiredWithoutTestFailuresNestedInput
}

export type DeployTestFailureUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  className?: Prisma.StringFieldUpdateOperationsInput | string
  methodName?: Prisma.StringFieldUpdateOperationsInput | string
  namespace?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  stackTrace?: Prisma.StringFieldUpdateOperationsInput | string
  time?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  deploymentId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DeployTestFailureCreateManyInput = {
  id?: string
  className: string
  methodName: string
  namespace?: string | null
  message: string
  stackTrace: string
  time: number
  type: string
  deploymentId: string
}

export type DeployTestFailureUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  className?: Prisma.StringFieldUpdateOperationsInput | string
  methodName?: Prisma.StringFieldUpdateOperationsInput | string
  namespace?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  stackTrace?: Prisma.StringFieldUpdateOperationsInput | string
  time?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DeployTestFailureUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  className?: Prisma.StringFieldUpdateOperationsInput | string
  methodName?: Prisma.StringFieldUpdateOperationsInput | string
  namespace?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  stackTrace?: Prisma.StringFieldUpdateOperationsInput | string
  time?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  deploymentId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DeployTestFailureListRelationFilter = {
  every?: Prisma.DeployTestFailureWhereInput
  some?: Prisma.DeployTestFailureWhereInput
  none?: Prisma.DeployTestFailureWhereInput
}

export type DeployTestFailureOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DeployTestFailureCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  className?: Prisma.SortOrder
  methodName?: Prisma.SortOrder
  namespace?: Prisma.SortOrder
  message?: Prisma.SortOrder
  stackTrace?: Prisma.SortOrder
  time?: Prisma.SortOrder
  type?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
}

export type DeployTestFailureAvgOrderByAggregateInput = {
  time?: Prisma.SortOrder
}

export type DeployTestFailureMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  className?: Prisma.SortOrder
  methodName?: Prisma.SortOrder
  namespace?: Prisma.SortOrder
  message?: Prisma.SortOrder
  stackTrace?: Prisma.SortOrder
  time?: Prisma.SortOrder
  type?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
}

export type DeployTestFailureMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  className?: Prisma.SortOrder
  methodName?: Prisma.SortOrder
  namespace?: Prisma.SortOrder
  message?: Prisma.SortOrder
  stackTrace?: Prisma.SortOrder
  time?: Prisma.SortOrder
  type?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
}

export type DeployTestFailureSumOrderByAggregateInput = {
  time?: Prisma.SortOrder
}

export type DeployTestFailureCreateNestedManyWithoutDeploymentInput = {
  create?: Prisma.XOR<Prisma.DeployTestFailureCreateWithoutDeploymentInput, Prisma.DeployTestFailureUncheckedCreateWithoutDeploymentInput> | Prisma.DeployTestFailureCreateWithoutDeploymentInput[] | Prisma.DeployTestFailureUncheckedCreateWithoutDeploymentInput[]
  connectOrCreate?: Prisma.DeployTestFailureCreateOrConnectWithoutDeploymentInput | Prisma.DeployTestFailureCreateOrConnectWithoutDeploymentInput[]
  createMany?: Prisma.DeployTestFailureCreateManyDeploymentInputEnvelope
  connect?: Prisma.DeployTestFailureWhereUniqueInput | Prisma.DeployTestFailureWhereUniqueInput[]
}

export type DeployTestFailureUncheckedCreateNestedManyWithoutDeploymentInput = {
  create?: Prisma.XOR<Prisma.DeployTestFailureCreateWithoutDeploymentInput, Prisma.DeployTestFailureUncheckedCreateWithoutDeploymentInput> | Prisma.DeployTestFailureCreateWithoutDeploymentInput[] | Prisma.DeployTestFailureUncheckedCreateWithoutDeploymentInput[]
  connectOrCreate?: Prisma.DeployTestFailureCreateOrConnectWithoutDeploymentInput | Prisma.DeployTestFailureCreateOrConnectWithoutDeploymentInput[]
  createMany?: Prisma.DeployTestFailureCreateManyDeploymentInputEnvelope
  connect?: Prisma.DeployTestFailureWhereUniqueInput | Prisma.DeployTestFailureWhereUniqueInput[]
}

export type DeployTestFailureUpdateManyWithoutDeploymentNestedInput = {
  create?: Prisma.XOR<Prisma.DeployTestFailureCreateWithoutDeploymentInput, Prisma.DeployTestFailureUncheckedCreateWithoutDeploymentInput> | Prisma.DeployTestFailureCreateWithoutDeploymentInput[] | Prisma.DeployTestFailureUncheckedCreateWithoutDeploymentInput[]
  connectOrCreate?: Prisma.DeployTestFailureCreateOrConnectWithoutDeploymentInput | Prisma.DeployTestFailureCreateOrConnectWithoutDeploymentInput[]
  upsert?: Prisma.DeployTestFailureUpsertWithWhereUniqueWithoutDeploymentInput | Prisma.DeployTestFailureUpsertWithWhereUniqueWithoutDeploymentInput[]
  createMany?: Prisma.DeployTestFailureCreateManyDeploymentInputEnvelope
  set?: Prisma.DeployTestFailureWhereUniqueInput | Prisma.DeployTestFailureWhereUniqueInput[]
  disconnect?: Prisma.DeployTestFailureWhereUniqueInput | Prisma.DeployTestFailureWhereUniqueInput[]
  delete?: Prisma.DeployTestFailureWhereUniqueInput | Prisma.DeployTestFailureWhereUniqueInput[]
  connect?: Prisma.DeployTestFailureWhereUniqueInput | Prisma.DeployTestFailureWhereUniqueInput[]
  update?: Prisma.DeployTestFailureUpdateWithWhereUniqueWithoutDeploymentInput | Prisma.DeployTestFailureUpdateWithWhereUniqueWithoutDeploymentInput[]
  updateMany?: Prisma.DeployTestFailureUpdateManyWithWhereWithoutDeploymentInput | Prisma.DeployTestFailureUpdateManyWithWhereWithoutDeploymentInput[]
  deleteMany?: Prisma.DeployTestFailureScalarWhereInput | Prisma.DeployTestFailureScalarWhereInput[]
}

export type DeployTestFailureUncheckedUpdateManyWithoutDeploymentNestedInput = {
  create?: Prisma.XOR<Prisma.DeployTestFailureCreateWithoutDeploymentInput, Prisma.DeployTestFailureUncheckedCreateWithoutDeploymentInput> | Prisma.DeployTestFailureCreateWithoutDeploymentInput[] | Prisma.DeployTestFailureUncheckedCreateWithoutDeploymentInput[]
  connectOrCreate?: Prisma.DeployTestFailureCreateOrConnectWithoutDeploymentInput | Prisma.DeployTestFailureCreateOrConnectWithoutDeploymentInput[]
  upsert?: Prisma.DeployTestFailureUpsertWithWhereUniqueWithoutDeploymentInput | Prisma.DeployTestFailureUpsertWithWhereUniqueWithoutDeploymentInput[]
  createMany?: Prisma.DeployTestFailureCreateManyDeploymentInputEnvelope
  set?: Prisma.DeployTestFailureWhereUniqueInput | Prisma.DeployTestFailureWhereUniqueInput[]
  disconnect?: Prisma.DeployTestFailureWhereUniqueInput | Prisma.DeployTestFailureWhereUniqueInput[]
  delete?: Prisma.DeployTestFailureWhereUniqueInput | Prisma.DeployTestFailureWhereUniqueInput[]
  connect?: Prisma.DeployTestFailureWhereUniqueInput | Prisma.DeployTestFailureWhereUniqueInput[]
  update?: Prisma.DeployTestFailureUpdateWithWhereUniqueWithoutDeploymentInput | Prisma.DeployTestFailureUpdateWithWhereUniqueWithoutDeploymentInput[]
  updateMany?: Prisma.DeployTestFailureUpdateManyWithWhereWithoutDeploymentInput | Prisma.DeployTestFailureUpdateManyWithWhereWithoutDeploymentInput[]
  deleteMany?: Prisma.DeployTestFailureScalarWhereInput | Prisma.DeployTestFailureScalarWhereInput[]
}

export type DeployTestFailureCreateWithoutDeploymentInput = {
  id?: string
  className: string
  methodName: string
  namespace?: string | null
  message: string
  stackTrace: string
  time: number
  type: string
}

export type DeployTestFailureUncheckedCreateWithoutDeploymentInput = {
  id?: string
  className: string
  methodName: string
  namespace?: string | null
  message: string
  stackTrace: string
  time: number
  type: string
}

export type DeployTestFailureCreateOrConnectWithoutDeploymentInput = {
  where: Prisma.DeployTestFailureWhereUniqueInput
  create: Prisma.XOR<Prisma.DeployTestFailureCreateWithoutDeploymentInput, Prisma.DeployTestFailureUncheckedCreateWithoutDeploymentInput>
}

export type DeployTestFailureCreateManyDeploymentInputEnvelope = {
  data: Prisma.DeployTestFailureCreateManyDeploymentInput | Prisma.DeployTestFailureCreateManyDeploymentInput[]
  skipDuplicates?: boolean
}

export type DeployTestFailureUpsertWithWhereUniqueWithoutDeploymentInput = {
  where: Prisma.DeployTestFailureWhereUniqueInput
  update: Prisma.XOR<Prisma.DeployTestFailureUpdateWithoutDeploymentInput, Prisma.DeployTestFailureUncheckedUpdateWithoutDeploymentInput>
  create: Prisma.XOR<Prisma.DeployTestFailureCreateWithoutDeploymentInput, Prisma.DeployTestFailureUncheckedCreateWithoutDeploymentInput>
}

export type DeployTestFailureUpdateWithWhereUniqueWithoutDeploymentInput = {
  where: Prisma.DeployTestFailureWhereUniqueInput
  data: Prisma.XOR<Prisma.DeployTestFailureUpdateWithoutDeploymentInput, Prisma.DeployTestFailureUncheckedUpdateWithoutDeploymentInput>
}

export type DeployTestFailureUpdateManyWithWhereWithoutDeploymentInput = {
  where: Prisma.DeployTestFailureScalarWhereInput
  data: Prisma.XOR<Prisma.DeployTestFailureUpdateManyMutationInput, Prisma.DeployTestFailureUncheckedUpdateManyWithoutDeploymentInput>
}

export type DeployTestFailureScalarWhereInput = {
  AND?: Prisma.DeployTestFailureScalarWhereInput | Prisma.DeployTestFailureScalarWhereInput[]
  OR?: Prisma.DeployTestFailureScalarWhereInput[]
  NOT?: Prisma.DeployTestFailureScalarWhereInput | Prisma.DeployTestFailureScalarWhereInput[]
  id?: Prisma.StringFilter<"DeployTestFailure"> | string
  className?: Prisma.StringFilter<"DeployTestFailure"> | string
  methodName?: Prisma.StringFilter<"DeployTestFailure"> | string
  namespace?: Prisma.StringNullableFilter<"DeployTestFailure"> | string | null
  message?: Prisma.StringFilter<"DeployTestFailure"> | string
  stackTrace?: Prisma.StringFilter<"DeployTestFailure"> | string
  time?: Prisma.IntFilter<"DeployTestFailure"> | number
  type?: Prisma.StringFilter<"DeployTestFailure"> | string
  deploymentId?: Prisma.StringFilter<"DeployTestFailure"> | string
}

export type DeployTestFailureCreateManyDeploymentInput = {
  id?: string
  className: string
  methodName: string
  namespace?: string | null
  message: string
  stackTrace: string
  time: number
  type: string
}

export type DeployTestFailureUpdateWithoutDeploymentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  className?: Prisma.StringFieldUpdateOperationsInput | string
  methodName?: Prisma.StringFieldUpdateOperationsInput | string
  namespace?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  stackTrace?: Prisma.StringFieldUpdateOperationsInput | string
  time?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DeployTestFailureUncheckedUpdateWithoutDeploymentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  className?: Prisma.StringFieldUpdateOperationsInput | string
  methodName?: Prisma.StringFieldUpdateOperationsInput | string
  namespace?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  stackTrace?: Prisma.StringFieldUpdateOperationsInput | string
  time?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DeployTestFailureUncheckedUpdateManyWithoutDeploymentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  className?: Prisma.StringFieldUpdateOperationsInput | string
  methodName?: Prisma.StringFieldUpdateOperationsInput | string
  namespace?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  message?: Prisma.StringFieldUpdateOperationsInput | string
  stackTrace?: Prisma.StringFieldUpdateOperationsInput | string
  time?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
}



export type DeployTestFailureSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  className?: boolean
  methodName?: boolean
  namespace?: boolean
  message?: boolean
  stackTrace?: boolean
  time?: boolean
  type?: boolean
  deploymentId?: boolean
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["deployTestFailure"]>

export type DeployTestFailureSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  className?: boolean
  methodName?: boolean
  namespace?: boolean
  message?: boolean
  stackTrace?: boolean
  time?: boolean
  type?: boolean
  deploymentId?: boolean
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["deployTestFailure"]>

export type DeployTestFailureSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  className?: boolean
  methodName?: boolean
  namespace?: boolean
  message?: boolean
  stackTrace?: boolean
  time?: boolean
  type?: boolean
  deploymentId?: boolean
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["deployTestFailure"]>

export type DeployTestFailureSelectScalar = {
  id?: boolean
  className?: boolean
  methodName?: boolean
  namespace?: boolean
  message?: boolean
  stackTrace?: boolean
  time?: boolean
  type?: boolean
  deploymentId?: boolean
}

export type DeployTestFailureOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "className" | "methodName" | "namespace" | "message" | "stackTrace" | "time" | "type" | "deploymentId", ExtArgs["result"]["deployTestFailure"]>
export type DeployTestFailureInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}
export type DeployTestFailureIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}
export type DeployTestFailureIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}

export type $DeployTestFailurePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DeployTestFailure"
  objects: {
    Deployment: Prisma.$DeploymentPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    className: string
    methodName: string
    namespace: string | null
    message: string
    stackTrace: string
    time: number
    type: string
    deploymentId: string
  }, ExtArgs["result"]["deployTestFailure"]>
  composites: {}
}

export type DeployTestFailureGetPayload<S extends boolean | null | undefined | DeployTestFailureDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DeployTestFailurePayload, S>

export type DeployTestFailureCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DeployTestFailureFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DeployTestFailureCountAggregateInputType | true
  }

export interface DeployTestFailureDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DeployTestFailure'], meta: { name: 'DeployTestFailure' } }
  /**
   * Find zero or one DeployTestFailure that matches the filter.
   * @param {DeployTestFailureFindUniqueArgs} args - Arguments to find a DeployTestFailure
   * @example
   * // Get one DeployTestFailure
   * const deployTestFailure = await prisma.deployTestFailure.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DeployTestFailureFindUniqueArgs>(args: Prisma.SelectSubset<T, DeployTestFailureFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DeployTestFailureClient<runtime.Types.Result.GetResult<Prisma.$DeployTestFailurePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DeployTestFailure that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DeployTestFailureFindUniqueOrThrowArgs} args - Arguments to find a DeployTestFailure
   * @example
   * // Get one DeployTestFailure
   * const deployTestFailure = await prisma.deployTestFailure.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DeployTestFailureFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DeployTestFailureFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DeployTestFailureClient<runtime.Types.Result.GetResult<Prisma.$DeployTestFailurePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DeployTestFailure that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployTestFailureFindFirstArgs} args - Arguments to find a DeployTestFailure
   * @example
   * // Get one DeployTestFailure
   * const deployTestFailure = await prisma.deployTestFailure.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DeployTestFailureFindFirstArgs>(args?: Prisma.SelectSubset<T, DeployTestFailureFindFirstArgs<ExtArgs>>): Prisma.Prisma__DeployTestFailureClient<runtime.Types.Result.GetResult<Prisma.$DeployTestFailurePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DeployTestFailure that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployTestFailureFindFirstOrThrowArgs} args - Arguments to find a DeployTestFailure
   * @example
   * // Get one DeployTestFailure
   * const deployTestFailure = await prisma.deployTestFailure.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DeployTestFailureFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DeployTestFailureFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DeployTestFailureClient<runtime.Types.Result.GetResult<Prisma.$DeployTestFailurePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DeployTestFailures that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployTestFailureFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DeployTestFailures
   * const deployTestFailures = await prisma.deployTestFailure.findMany()
   * 
   * // Get first 10 DeployTestFailures
   * const deployTestFailures = await prisma.deployTestFailure.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const deployTestFailureWithIdOnly = await prisma.deployTestFailure.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DeployTestFailureFindManyArgs>(args?: Prisma.SelectSubset<T, DeployTestFailureFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DeployTestFailurePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DeployTestFailure.
   * @param {DeployTestFailureCreateArgs} args - Arguments to create a DeployTestFailure.
   * @example
   * // Create one DeployTestFailure
   * const DeployTestFailure = await prisma.deployTestFailure.create({
   *   data: {
   *     // ... data to create a DeployTestFailure
   *   }
   * })
   * 
   */
  create<T extends DeployTestFailureCreateArgs>(args: Prisma.SelectSubset<T, DeployTestFailureCreateArgs<ExtArgs>>): Prisma.Prisma__DeployTestFailureClient<runtime.Types.Result.GetResult<Prisma.$DeployTestFailurePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DeployTestFailures.
   * @param {DeployTestFailureCreateManyArgs} args - Arguments to create many DeployTestFailures.
   * @example
   * // Create many DeployTestFailures
   * const deployTestFailure = await prisma.deployTestFailure.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DeployTestFailureCreateManyArgs>(args?: Prisma.SelectSubset<T, DeployTestFailureCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DeployTestFailures and returns the data saved in the database.
   * @param {DeployTestFailureCreateManyAndReturnArgs} args - Arguments to create many DeployTestFailures.
   * @example
   * // Create many DeployTestFailures
   * const deployTestFailure = await prisma.deployTestFailure.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DeployTestFailures and only return the `id`
   * const deployTestFailureWithIdOnly = await prisma.deployTestFailure.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DeployTestFailureCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DeployTestFailureCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DeployTestFailurePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DeployTestFailure.
   * @param {DeployTestFailureDeleteArgs} args - Arguments to delete one DeployTestFailure.
   * @example
   * // Delete one DeployTestFailure
   * const DeployTestFailure = await prisma.deployTestFailure.delete({
   *   where: {
   *     // ... filter to delete one DeployTestFailure
   *   }
   * })
   * 
   */
  delete<T extends DeployTestFailureDeleteArgs>(args: Prisma.SelectSubset<T, DeployTestFailureDeleteArgs<ExtArgs>>): Prisma.Prisma__DeployTestFailureClient<runtime.Types.Result.GetResult<Prisma.$DeployTestFailurePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DeployTestFailure.
   * @param {DeployTestFailureUpdateArgs} args - Arguments to update one DeployTestFailure.
   * @example
   * // Update one DeployTestFailure
   * const deployTestFailure = await prisma.deployTestFailure.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DeployTestFailureUpdateArgs>(args: Prisma.SelectSubset<T, DeployTestFailureUpdateArgs<ExtArgs>>): Prisma.Prisma__DeployTestFailureClient<runtime.Types.Result.GetResult<Prisma.$DeployTestFailurePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DeployTestFailures.
   * @param {DeployTestFailureDeleteManyArgs} args - Arguments to filter DeployTestFailures to delete.
   * @example
   * // Delete a few DeployTestFailures
   * const { count } = await prisma.deployTestFailure.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DeployTestFailureDeleteManyArgs>(args?: Prisma.SelectSubset<T, DeployTestFailureDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DeployTestFailures.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployTestFailureUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DeployTestFailures
   * const deployTestFailure = await prisma.deployTestFailure.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DeployTestFailureUpdateManyArgs>(args: Prisma.SelectSubset<T, DeployTestFailureUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DeployTestFailures and returns the data updated in the database.
   * @param {DeployTestFailureUpdateManyAndReturnArgs} args - Arguments to update many DeployTestFailures.
   * @example
   * // Update many DeployTestFailures
   * const deployTestFailure = await prisma.deployTestFailure.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DeployTestFailures and only return the `id`
   * const deployTestFailureWithIdOnly = await prisma.deployTestFailure.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DeployTestFailureUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DeployTestFailureUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DeployTestFailurePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DeployTestFailure.
   * @param {DeployTestFailureUpsertArgs} args - Arguments to update or create a DeployTestFailure.
   * @example
   * // Update or create a DeployTestFailure
   * const deployTestFailure = await prisma.deployTestFailure.upsert({
   *   create: {
   *     // ... data to create a DeployTestFailure
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DeployTestFailure we want to update
   *   }
   * })
   */
  upsert<T extends DeployTestFailureUpsertArgs>(args: Prisma.SelectSubset<T, DeployTestFailureUpsertArgs<ExtArgs>>): Prisma.Prisma__DeployTestFailureClient<runtime.Types.Result.GetResult<Prisma.$DeployTestFailurePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DeployTestFailures.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployTestFailureCountArgs} args - Arguments to filter DeployTestFailures to count.
   * @example
   * // Count the number of DeployTestFailures
   * const count = await prisma.deployTestFailure.count({
   *   where: {
   *     // ... the filter for the DeployTestFailures we want to count
   *   }
   * })
  **/
  count<T extends DeployTestFailureCountArgs>(
    args?: Prisma.Subset<T, DeployTestFailureCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DeployTestFailureCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DeployTestFailure.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployTestFailureAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DeployTestFailureAggregateArgs>(args: Prisma.Subset<T, DeployTestFailureAggregateArgs>): Prisma.PrismaPromise<GetDeployTestFailureAggregateType<T>>

  /**
   * Group by DeployTestFailure.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployTestFailureGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DeployTestFailureGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DeployTestFailureGroupByArgs['orderBy'] }
      : { orderBy?: DeployTestFailureGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DeployTestFailureGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDeployTestFailureGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DeployTestFailure model
 */
readonly fields: DeployTestFailureFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DeployTestFailure.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DeployTestFailureClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Deployment<T extends Prisma.DeploymentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DeploymentDefaultArgs<ExtArgs>>): Prisma.Prisma__DeploymentClient<runtime.Types.Result.GetResult<Prisma.$DeploymentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DeployTestFailure model
 */
export interface DeployTestFailureFieldRefs {
  readonly id: Prisma.FieldRef<"DeployTestFailure", 'String'>
  readonly className: Prisma.FieldRef<"DeployTestFailure", 'String'>
  readonly methodName: Prisma.FieldRef<"DeployTestFailure", 'String'>
  readonly namespace: Prisma.FieldRef<"DeployTestFailure", 'String'>
  readonly message: Prisma.FieldRef<"DeployTestFailure", 'String'>
  readonly stackTrace: Prisma.FieldRef<"DeployTestFailure", 'String'>
  readonly time: Prisma.FieldRef<"DeployTestFailure", 'Int'>
  readonly type: Prisma.FieldRef<"DeployTestFailure", 'String'>
  readonly deploymentId: Prisma.FieldRef<"DeployTestFailure", 'String'>
}
    

// Custom InputTypes
/**
 * DeployTestFailure findUnique
 */
export type DeployTestFailureFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployTestFailure
   */
  select?: Prisma.DeployTestFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployTestFailure
   */
  omit?: Prisma.DeployTestFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployTestFailureInclude<ExtArgs> | null
  /**
   * Filter, which DeployTestFailure to fetch.
   */
  where: Prisma.DeployTestFailureWhereUniqueInput
}

/**
 * DeployTestFailure findUniqueOrThrow
 */
export type DeployTestFailureFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployTestFailure
   */
  select?: Prisma.DeployTestFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployTestFailure
   */
  omit?: Prisma.DeployTestFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployTestFailureInclude<ExtArgs> | null
  /**
   * Filter, which DeployTestFailure to fetch.
   */
  where: Prisma.DeployTestFailureWhereUniqueInput
}

/**
 * DeployTestFailure findFirst
 */
export type DeployTestFailureFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployTestFailure
   */
  select?: Prisma.DeployTestFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployTestFailure
   */
  omit?: Prisma.DeployTestFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployTestFailureInclude<ExtArgs> | null
  /**
   * Filter, which DeployTestFailure to fetch.
   */
  where?: Prisma.DeployTestFailureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DeployTestFailures to fetch.
   */
  orderBy?: Prisma.DeployTestFailureOrderByWithRelationInput | Prisma.DeployTestFailureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DeployTestFailures.
   */
  cursor?: Prisma.DeployTestFailureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DeployTestFailures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DeployTestFailures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DeployTestFailures.
   */
  distinct?: Prisma.DeployTestFailureScalarFieldEnum | Prisma.DeployTestFailureScalarFieldEnum[]
}

/**
 * DeployTestFailure findFirstOrThrow
 */
export type DeployTestFailureFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployTestFailure
   */
  select?: Prisma.DeployTestFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployTestFailure
   */
  omit?: Prisma.DeployTestFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployTestFailureInclude<ExtArgs> | null
  /**
   * Filter, which DeployTestFailure to fetch.
   */
  where?: Prisma.DeployTestFailureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DeployTestFailures to fetch.
   */
  orderBy?: Prisma.DeployTestFailureOrderByWithRelationInput | Prisma.DeployTestFailureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DeployTestFailures.
   */
  cursor?: Prisma.DeployTestFailureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DeployTestFailures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DeployTestFailures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DeployTestFailures.
   */
  distinct?: Prisma.DeployTestFailureScalarFieldEnum | Prisma.DeployTestFailureScalarFieldEnum[]
}

/**
 * DeployTestFailure findMany
 */
export type DeployTestFailureFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployTestFailure
   */
  select?: Prisma.DeployTestFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployTestFailure
   */
  omit?: Prisma.DeployTestFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployTestFailureInclude<ExtArgs> | null
  /**
   * Filter, which DeployTestFailures to fetch.
   */
  where?: Prisma.DeployTestFailureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DeployTestFailures to fetch.
   */
  orderBy?: Prisma.DeployTestFailureOrderByWithRelationInput | Prisma.DeployTestFailureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DeployTestFailures.
   */
  cursor?: Prisma.DeployTestFailureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DeployTestFailures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DeployTestFailures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DeployTestFailures.
   */
  distinct?: Prisma.DeployTestFailureScalarFieldEnum | Prisma.DeployTestFailureScalarFieldEnum[]
}

/**
 * DeployTestFailure create
 */
export type DeployTestFailureCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployTestFailure
   */
  select?: Prisma.DeployTestFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployTestFailure
   */
  omit?: Prisma.DeployTestFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployTestFailureInclude<ExtArgs> | null
  /**
   * The data needed to create a DeployTestFailure.
   */
  data: Prisma.XOR<Prisma.DeployTestFailureCreateInput, Prisma.DeployTestFailureUncheckedCreateInput>
}

/**
 * DeployTestFailure createMany
 */
export type DeployTestFailureCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DeployTestFailures.
   */
  data: Prisma.DeployTestFailureCreateManyInput | Prisma.DeployTestFailureCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DeployTestFailure createManyAndReturn
 */
export type DeployTestFailureCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployTestFailure
   */
  select?: Prisma.DeployTestFailureSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DeployTestFailure
   */
  omit?: Prisma.DeployTestFailureOmit<ExtArgs> | null
  /**
   * The data used to create many DeployTestFailures.
   */
  data: Prisma.DeployTestFailureCreateManyInput | Prisma.DeployTestFailureCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployTestFailureIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DeployTestFailure update
 */
export type DeployTestFailureUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployTestFailure
   */
  select?: Prisma.DeployTestFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployTestFailure
   */
  omit?: Prisma.DeployTestFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployTestFailureInclude<ExtArgs> | null
  /**
   * The data needed to update a DeployTestFailure.
   */
  data: Prisma.XOR<Prisma.DeployTestFailureUpdateInput, Prisma.DeployTestFailureUncheckedUpdateInput>
  /**
   * Choose, which DeployTestFailure to update.
   */
  where: Prisma.DeployTestFailureWhereUniqueInput
}

/**
 * DeployTestFailure updateMany
 */
export type DeployTestFailureUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DeployTestFailures.
   */
  data: Prisma.XOR<Prisma.DeployTestFailureUpdateManyMutationInput, Prisma.DeployTestFailureUncheckedUpdateManyInput>
  /**
   * Filter which DeployTestFailures to update
   */
  where?: Prisma.DeployTestFailureWhereInput
  /**
   * Limit how many DeployTestFailures to update.
   */
  limit?: number
}

/**
 * DeployTestFailure updateManyAndReturn
 */
export type DeployTestFailureUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployTestFailure
   */
  select?: Prisma.DeployTestFailureSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DeployTestFailure
   */
  omit?: Prisma.DeployTestFailureOmit<ExtArgs> | null
  /**
   * The data used to update DeployTestFailures.
   */
  data: Prisma.XOR<Prisma.DeployTestFailureUpdateManyMutationInput, Prisma.DeployTestFailureUncheckedUpdateManyInput>
  /**
   * Filter which DeployTestFailures to update
   */
  where?: Prisma.DeployTestFailureWhereInput
  /**
   * Limit how many DeployTestFailures to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployTestFailureIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DeployTestFailure upsert
 */
export type DeployTestFailureUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployTestFailure
   */
  select?: Prisma.DeployTestFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployTestFailure
   */
  omit?: Prisma.DeployTestFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployTestFailureInclude<ExtArgs> | null
  /**
   * The filter to search for the DeployTestFailure to update in case it exists.
   */
  where: Prisma.DeployTestFailureWhereUniqueInput
  /**
   * In case the DeployTestFailure found by the `where` argument doesn't exist, create a new DeployTestFailure with this data.
   */
  create: Prisma.XOR<Prisma.DeployTestFailureCreateInput, Prisma.DeployTestFailureUncheckedCreateInput>
  /**
   * In case the DeployTestFailure was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DeployTestFailureUpdateInput, Prisma.DeployTestFailureUncheckedUpdateInput>
}

/**
 * DeployTestFailure delete
 */
export type DeployTestFailureDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployTestFailure
   */
  select?: Prisma.DeployTestFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployTestFailure
   */
  omit?: Prisma.DeployTestFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployTestFailureInclude<ExtArgs> | null
  /**
   * Filter which DeployTestFailure to delete.
   */
  where: Prisma.DeployTestFailureWhereUniqueInput
}

/**
 * DeployTestFailure deleteMany
 */
export type DeployTestFailureDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DeployTestFailures to delete
   */
  where?: Prisma.DeployTestFailureWhereInput
  /**
   * Limit how many DeployTestFailures to delete.
   */
  limit?: number
}

/**
 * DeployTestFailure without action
 */
export type DeployTestFailureDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployTestFailure
   */
  select?: Prisma.DeployTestFailureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployTestFailure
   */
  omit?: Prisma.DeployTestFailureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployTestFailureInclude<ExtArgs> | null
}
