
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DeployCodeCoverage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DeployCodeCoverage
 * 
 */
export type DeployCodeCoverageModel = runtime.Types.Result.DefaultSelection<Prisma.$DeployCodeCoveragePayload>

export type AggregateDeployCodeCoverage = {
  _count: DeployCodeCoverageCountAggregateOutputType | null
  _avg: DeployCodeCoverageAvgAggregateOutputType | null
  _sum: DeployCodeCoverageSumAggregateOutputType | null
  _min: DeployCodeCoverageMinAggregateOutputType | null
  _max: DeployCodeCoverageMaxAggregateOutputType | null
}

export type DeployCodeCoverageAvgAggregateOutputType = {
  numLocations: number | null
  numLocationsNotCovered: number | null
}

export type DeployCodeCoverageSumAggregateOutputType = {
  numLocations: number | null
  numLocationsNotCovered: number | null
}

export type DeployCodeCoverageMinAggregateOutputType = {
  id: string | null
  className: string | null
  numLocations: number | null
  numLocationsNotCovered: number | null
  deploymentId: string | null
}

export type DeployCodeCoverageMaxAggregateOutputType = {
  id: string | null
  className: string | null
  numLocations: number | null
  numLocationsNotCovered: number | null
  deploymentId: string | null
}

export type DeployCodeCoverageCountAggregateOutputType = {
  id: number
  className: number
  numLocations: number
  numLocationsNotCovered: number
  deploymentId: number
  _all: number
}


export type DeployCodeCoverageAvgAggregateInputType = {
  numLocations?: true
  numLocationsNotCovered?: true
}

export type DeployCodeCoverageSumAggregateInputType = {
  numLocations?: true
  numLocationsNotCovered?: true
}

export type DeployCodeCoverageMinAggregateInputType = {
  id?: true
  className?: true
  numLocations?: true
  numLocationsNotCovered?: true
  deploymentId?: true
}

export type DeployCodeCoverageMaxAggregateInputType = {
  id?: true
  className?: true
  numLocations?: true
  numLocationsNotCovered?: true
  deploymentId?: true
}

export type DeployCodeCoverageCountAggregateInputType = {
  id?: true
  className?: true
  numLocations?: true
  numLocationsNotCovered?: true
  deploymentId?: true
  _all?: true
}

export type DeployCodeCoverageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DeployCodeCoverage to aggregate.
   */
  where?: Prisma.DeployCodeCoverageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DeployCodeCoverages to fetch.
   */
  orderBy?: Prisma.DeployCodeCoverageOrderByWithRelationInput | Prisma.DeployCodeCoverageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DeployCodeCoverageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DeployCodeCoverages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DeployCodeCoverages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DeployCodeCoverages
  **/
  _count?: true | DeployCodeCoverageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DeployCodeCoverageAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DeployCodeCoverageSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DeployCodeCoverageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DeployCodeCoverageMaxAggregateInputType
}

export type GetDeployCodeCoverageAggregateType<T extends DeployCodeCoverageAggregateArgs> = {
      [P in keyof T & keyof AggregateDeployCodeCoverage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDeployCodeCoverage[P]>
    : Prisma.GetScalarType<T[P], AggregateDeployCodeCoverage[P]>
}




export type DeployCodeCoverageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DeployCodeCoverageWhereInput
  orderBy?: Prisma.DeployCodeCoverageOrderByWithAggregationInput | Prisma.DeployCodeCoverageOrderByWithAggregationInput[]
  by: Prisma.DeployCodeCoverageScalarFieldEnum[] | Prisma.DeployCodeCoverageScalarFieldEnum
  having?: Prisma.DeployCodeCoverageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DeployCodeCoverageCountAggregateInputType | true
  _avg?: DeployCodeCoverageAvgAggregateInputType
  _sum?: DeployCodeCoverageSumAggregateInputType
  _min?: DeployCodeCoverageMinAggregateInputType
  _max?: DeployCodeCoverageMaxAggregateInputType
}

export type DeployCodeCoverageGroupByOutputType = {
  id: string
  className: string
  numLocations: number
  numLocationsNotCovered: number
  deploymentId: string
  _count: DeployCodeCoverageCountAggregateOutputType | null
  _avg: DeployCodeCoverageAvgAggregateOutputType | null
  _sum: DeployCodeCoverageSumAggregateOutputType | null
  _min: DeployCodeCoverageMinAggregateOutputType | null
  _max: DeployCodeCoverageMaxAggregateOutputType | null
}

export type GetDeployCodeCoverageGroupByPayload<T extends DeployCodeCoverageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DeployCodeCoverageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DeployCodeCoverageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DeployCodeCoverageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DeployCodeCoverageGroupByOutputType[P]>
      }
    >
  >



export type DeployCodeCoverageWhereInput = {
  AND?: Prisma.DeployCodeCoverageWhereInput | Prisma.DeployCodeCoverageWhereInput[]
  OR?: Prisma.DeployCodeCoverageWhereInput[]
  NOT?: Prisma.DeployCodeCoverageWhereInput | Prisma.DeployCodeCoverageWhereInput[]
  id?: Prisma.StringFilter<"DeployCodeCoverage"> | string
  className?: Prisma.StringFilter<"DeployCodeCoverage"> | string
  numLocations?: Prisma.IntFilter<"DeployCodeCoverage"> | number
  numLocationsNotCovered?: Prisma.IntFilter<"DeployCodeCoverage"> | number
  deploymentId?: Prisma.StringFilter<"DeployCodeCoverage"> | string
  Deployment?: Prisma.XOR<Prisma.DeploymentScalarRelationFilter, Prisma.DeploymentWhereInput>
}

export type DeployCodeCoverageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  className?: Prisma.SortOrder
  numLocations?: Prisma.SortOrder
  numLocationsNotCovered?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
  Deployment?: Prisma.DeploymentOrderByWithRelationInput
}

export type DeployCodeCoverageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DeployCodeCoverageWhereInput | Prisma.DeployCodeCoverageWhereInput[]
  OR?: Prisma.DeployCodeCoverageWhereInput[]
  NOT?: Prisma.DeployCodeCoverageWhereInput | Prisma.DeployCodeCoverageWhereInput[]
  className?: Prisma.StringFilter<"DeployCodeCoverage"> | string
  numLocations?: Prisma.IntFilter<"DeployCodeCoverage"> | number
  numLocationsNotCovered?: Prisma.IntFilter<"DeployCodeCoverage"> | number
  deploymentId?: Prisma.StringFilter<"DeployCodeCoverage"> | string
  Deployment?: Prisma.XOR<Prisma.DeploymentScalarRelationFilter, Prisma.DeploymentWhereInput>
}, "id">

export type DeployCodeCoverageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  className?: Prisma.SortOrder
  numLocations?: Prisma.SortOrder
  numLocationsNotCovered?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
  _count?: Prisma.DeployCodeCoverageCountOrderByAggregateInput
  _avg?: Prisma.DeployCodeCoverageAvgOrderByAggregateInput
  _max?: Prisma.DeployCodeCoverageMaxOrderByAggregateInput
  _min?: Prisma.DeployCodeCoverageMinOrderByAggregateInput
  _sum?: Prisma.DeployCodeCoverageSumOrderByAggregateInput
}

export type DeployCodeCoverageScalarWhereWithAggregatesInput = {
  AND?: Prisma.DeployCodeCoverageScalarWhereWithAggregatesInput | Prisma.DeployCodeCoverageScalarWhereWithAggregatesInput[]
  OR?: Prisma.DeployCodeCoverageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DeployCodeCoverageScalarWhereWithAggregatesInput | Prisma.DeployCodeCoverageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DeployCodeCoverage"> | string
  className?: Prisma.StringWithAggregatesFilter<"DeployCodeCoverage"> | string
  numLocations?: Prisma.IntWithAggregatesFilter<"DeployCodeCoverage"> | number
  numLocationsNotCovered?: Prisma.IntWithAggregatesFilter<"DeployCodeCoverage"> | number
  deploymentId?: Prisma.StringWithAggregatesFilter<"DeployCodeCoverage"> | string
}

export type DeployCodeCoverageCreateInput = {
  id?: string
  className: string
  numLocations: number
  numLocationsNotCovered: number
  Deployment: Prisma.DeploymentCreateNestedOneWithoutCodeCoveragesInput
}

export type DeployCodeCoverageUncheckedCreateInput = {
  id?: string
  className: string
  numLocations: number
  numLocationsNotCovered: number
  deploymentId: string
}

export type DeployCodeCoverageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  className?: Prisma.StringFieldUpdateOperationsInput | string
  numLocations?: Prisma.IntFieldUpdateOperationsInput | number
  numLocationsNotCovered?: Prisma.IntFieldUpdateOperationsInput | number
  Deployment?: Prisma.DeploymentUpdateOneRequiredWithoutCodeCoveragesNestedInput
}

export type DeployCodeCoverageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  className?: Prisma.StringFieldUpdateOperationsInput | string
  numLocations?: Prisma.IntFieldUpdateOperationsInput | number
  numLocationsNotCovered?: Prisma.IntFieldUpdateOperationsInput | number
  deploymentId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DeployCodeCoverageCreateManyInput = {
  id?: string
  className: string
  numLocations: number
  numLocationsNotCovered: number
  deploymentId: string
}

export type DeployCodeCoverageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  className?: Prisma.StringFieldUpdateOperationsInput | string
  numLocations?: Prisma.IntFieldUpdateOperationsInput | number
  numLocationsNotCovered?: Prisma.IntFieldUpdateOperationsInput | number
}

export type DeployCodeCoverageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  className?: Prisma.StringFieldUpdateOperationsInput | string
  numLocations?: Prisma.IntFieldUpdateOperationsInput | number
  numLocationsNotCovered?: Prisma.IntFieldUpdateOperationsInput | number
  deploymentId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type DeployCodeCoverageListRelationFilter = {
  every?: Prisma.DeployCodeCoverageWhereInput
  some?: Prisma.DeployCodeCoverageWhereInput
  none?: Prisma.DeployCodeCoverageWhereInput
}

export type DeployCodeCoverageOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DeployCodeCoverageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  className?: Prisma.SortOrder
  numLocations?: Prisma.SortOrder
  numLocationsNotCovered?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
}

export type DeployCodeCoverageAvgOrderByAggregateInput = {
  numLocations?: Prisma.SortOrder
  numLocationsNotCovered?: Prisma.SortOrder
}

export type DeployCodeCoverageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  className?: Prisma.SortOrder
  numLocations?: Prisma.SortOrder
  numLocationsNotCovered?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
}

export type DeployCodeCoverageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  className?: Prisma.SortOrder
  numLocations?: Prisma.SortOrder
  numLocationsNotCovered?: Prisma.SortOrder
  deploymentId?: Prisma.SortOrder
}

export type DeployCodeCoverageSumOrderByAggregateInput = {
  numLocations?: Prisma.SortOrder
  numLocationsNotCovered?: Prisma.SortOrder
}

export type DeployCodeCoverageCreateNestedManyWithoutDeploymentInput = {
  create?: Prisma.XOR<Prisma.DeployCodeCoverageCreateWithoutDeploymentInput, Prisma.DeployCodeCoverageUncheckedCreateWithoutDeploymentInput> | Prisma.DeployCodeCoverageCreateWithoutDeploymentInput[] | Prisma.DeployCodeCoverageUncheckedCreateWithoutDeploymentInput[]
  connectOrCreate?: Prisma.DeployCodeCoverageCreateOrConnectWithoutDeploymentInput | Prisma.DeployCodeCoverageCreateOrConnectWithoutDeploymentInput[]
  createMany?: Prisma.DeployCodeCoverageCreateManyDeploymentInputEnvelope
  connect?: Prisma.DeployCodeCoverageWhereUniqueInput | Prisma.DeployCodeCoverageWhereUniqueInput[]
}

export type DeployCodeCoverageUncheckedCreateNestedManyWithoutDeploymentInput = {
  create?: Prisma.XOR<Prisma.DeployCodeCoverageCreateWithoutDeploymentInput, Prisma.DeployCodeCoverageUncheckedCreateWithoutDeploymentInput> | Prisma.DeployCodeCoverageCreateWithoutDeploymentInput[] | Prisma.DeployCodeCoverageUncheckedCreateWithoutDeploymentInput[]
  connectOrCreate?: Prisma.DeployCodeCoverageCreateOrConnectWithoutDeploymentInput | Prisma.DeployCodeCoverageCreateOrConnectWithoutDeploymentInput[]
  createMany?: Prisma.DeployCodeCoverageCreateManyDeploymentInputEnvelope
  connect?: Prisma.DeployCodeCoverageWhereUniqueInput | Prisma.DeployCodeCoverageWhereUniqueInput[]
}

export type DeployCodeCoverageUpdateManyWithoutDeploymentNestedInput = {
  create?: Prisma.XOR<Prisma.DeployCodeCoverageCreateWithoutDeploymentInput, Prisma.DeployCodeCoverageUncheckedCreateWithoutDeploymentInput> | Prisma.DeployCodeCoverageCreateWithoutDeploymentInput[] | Prisma.DeployCodeCoverageUncheckedCreateWithoutDeploymentInput[]
  connectOrCreate?: Prisma.DeployCodeCoverageCreateOrConnectWithoutDeploymentInput | Prisma.DeployCodeCoverageCreateOrConnectWithoutDeploymentInput[]
  upsert?: Prisma.DeployCodeCoverageUpsertWithWhereUniqueWithoutDeploymentInput | Prisma.DeployCodeCoverageUpsertWithWhereUniqueWithoutDeploymentInput[]
  createMany?: Prisma.DeployCodeCoverageCreateManyDeploymentInputEnvelope
  set?: Prisma.DeployCodeCoverageWhereUniqueInput | Prisma.DeployCodeCoverageWhereUniqueInput[]
  disconnect?: Prisma.DeployCodeCoverageWhereUniqueInput | Prisma.DeployCodeCoverageWhereUniqueInput[]
  delete?: Prisma.DeployCodeCoverageWhereUniqueInput | Prisma.DeployCodeCoverageWhereUniqueInput[]
  connect?: Prisma.DeployCodeCoverageWhereUniqueInput | Prisma.DeployCodeCoverageWhereUniqueInput[]
  update?: Prisma.DeployCodeCoverageUpdateWithWhereUniqueWithoutDeploymentInput | Prisma.DeployCodeCoverageUpdateWithWhereUniqueWithoutDeploymentInput[]
  updateMany?: Prisma.DeployCodeCoverageUpdateManyWithWhereWithoutDeploymentInput | Prisma.DeployCodeCoverageUpdateManyWithWhereWithoutDeploymentInput[]
  deleteMany?: Prisma.DeployCodeCoverageScalarWhereInput | Prisma.DeployCodeCoverageScalarWhereInput[]
}

export type DeployCodeCoverageUncheckedUpdateManyWithoutDeploymentNestedInput = {
  create?: Prisma.XOR<Prisma.DeployCodeCoverageCreateWithoutDeploymentInput, Prisma.DeployCodeCoverageUncheckedCreateWithoutDeploymentInput> | Prisma.DeployCodeCoverageCreateWithoutDeploymentInput[] | Prisma.DeployCodeCoverageUncheckedCreateWithoutDeploymentInput[]
  connectOrCreate?: Prisma.DeployCodeCoverageCreateOrConnectWithoutDeploymentInput | Prisma.DeployCodeCoverageCreateOrConnectWithoutDeploymentInput[]
  upsert?: Prisma.DeployCodeCoverageUpsertWithWhereUniqueWithoutDeploymentInput | Prisma.DeployCodeCoverageUpsertWithWhereUniqueWithoutDeploymentInput[]
  createMany?: Prisma.DeployCodeCoverageCreateManyDeploymentInputEnvelope
  set?: Prisma.DeployCodeCoverageWhereUniqueInput | Prisma.DeployCodeCoverageWhereUniqueInput[]
  disconnect?: Prisma.DeployCodeCoverageWhereUniqueInput | Prisma.DeployCodeCoverageWhereUniqueInput[]
  delete?: Prisma.DeployCodeCoverageWhereUniqueInput | Prisma.DeployCodeCoverageWhereUniqueInput[]
  connect?: Prisma.DeployCodeCoverageWhereUniqueInput | Prisma.DeployCodeCoverageWhereUniqueInput[]
  update?: Prisma.DeployCodeCoverageUpdateWithWhereUniqueWithoutDeploymentInput | Prisma.DeployCodeCoverageUpdateWithWhereUniqueWithoutDeploymentInput[]
  updateMany?: Prisma.DeployCodeCoverageUpdateManyWithWhereWithoutDeploymentInput | Prisma.DeployCodeCoverageUpdateManyWithWhereWithoutDeploymentInput[]
  deleteMany?: Prisma.DeployCodeCoverageScalarWhereInput | Prisma.DeployCodeCoverageScalarWhereInput[]
}

export type DeployCodeCoverageCreateWithoutDeploymentInput = {
  id?: string
  className: string
  numLocations: number
  numLocationsNotCovered: number
}

export type DeployCodeCoverageUncheckedCreateWithoutDeploymentInput = {
  id?: string
  className: string
  numLocations: number
  numLocationsNotCovered: number
}

export type DeployCodeCoverageCreateOrConnectWithoutDeploymentInput = {
  where: Prisma.DeployCodeCoverageWhereUniqueInput
  create: Prisma.XOR<Prisma.DeployCodeCoverageCreateWithoutDeploymentInput, Prisma.DeployCodeCoverageUncheckedCreateWithoutDeploymentInput>
}

export type DeployCodeCoverageCreateManyDeploymentInputEnvelope = {
  data: Prisma.DeployCodeCoverageCreateManyDeploymentInput | Prisma.DeployCodeCoverageCreateManyDeploymentInput[]
  skipDuplicates?: boolean
}

export type DeployCodeCoverageUpsertWithWhereUniqueWithoutDeploymentInput = {
  where: Prisma.DeployCodeCoverageWhereUniqueInput
  update: Prisma.XOR<Prisma.DeployCodeCoverageUpdateWithoutDeploymentInput, Prisma.DeployCodeCoverageUncheckedUpdateWithoutDeploymentInput>
  create: Prisma.XOR<Prisma.DeployCodeCoverageCreateWithoutDeploymentInput, Prisma.DeployCodeCoverageUncheckedCreateWithoutDeploymentInput>
}

export type DeployCodeCoverageUpdateWithWhereUniqueWithoutDeploymentInput = {
  where: Prisma.DeployCodeCoverageWhereUniqueInput
  data: Prisma.XOR<Prisma.DeployCodeCoverageUpdateWithoutDeploymentInput, Prisma.DeployCodeCoverageUncheckedUpdateWithoutDeploymentInput>
}

export type DeployCodeCoverageUpdateManyWithWhereWithoutDeploymentInput = {
  where: Prisma.DeployCodeCoverageScalarWhereInput
  data: Prisma.XOR<Prisma.DeployCodeCoverageUpdateManyMutationInput, Prisma.DeployCodeCoverageUncheckedUpdateManyWithoutDeploymentInput>
}

export type DeployCodeCoverageScalarWhereInput = {
  AND?: Prisma.DeployCodeCoverageScalarWhereInput | Prisma.DeployCodeCoverageScalarWhereInput[]
  OR?: Prisma.DeployCodeCoverageScalarWhereInput[]
  NOT?: Prisma.DeployCodeCoverageScalarWhereInput | Prisma.DeployCodeCoverageScalarWhereInput[]
  id?: Prisma.StringFilter<"DeployCodeCoverage"> | string
  className?: Prisma.StringFilter<"DeployCodeCoverage"> | string
  numLocations?: Prisma.IntFilter<"DeployCodeCoverage"> | number
  numLocationsNotCovered?: Prisma.IntFilter<"DeployCodeCoverage"> | number
  deploymentId?: Prisma.StringFilter<"DeployCodeCoverage"> | string
}

export type DeployCodeCoverageCreateManyDeploymentInput = {
  id?: string
  className: string
  numLocations: number
  numLocationsNotCovered: number
}

export type DeployCodeCoverageUpdateWithoutDeploymentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  className?: Prisma.StringFieldUpdateOperationsInput | string
  numLocations?: Prisma.IntFieldUpdateOperationsInput | number
  numLocationsNotCovered?: Prisma.IntFieldUpdateOperationsInput | number
}

export type DeployCodeCoverageUncheckedUpdateWithoutDeploymentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  className?: Prisma.StringFieldUpdateOperationsInput | string
  numLocations?: Prisma.IntFieldUpdateOperationsInput | number
  numLocationsNotCovered?: Prisma.IntFieldUpdateOperationsInput | number
}

export type DeployCodeCoverageUncheckedUpdateManyWithoutDeploymentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  className?: Prisma.StringFieldUpdateOperationsInput | string
  numLocations?: Prisma.IntFieldUpdateOperationsInput | number
  numLocationsNotCovered?: Prisma.IntFieldUpdateOperationsInput | number
}



export type DeployCodeCoverageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  className?: boolean
  numLocations?: boolean
  numLocationsNotCovered?: boolean
  deploymentId?: boolean
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["deployCodeCoverage"]>

export type DeployCodeCoverageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  className?: boolean
  numLocations?: boolean
  numLocationsNotCovered?: boolean
  deploymentId?: boolean
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["deployCodeCoverage"]>

export type DeployCodeCoverageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  className?: boolean
  numLocations?: boolean
  numLocationsNotCovered?: boolean
  deploymentId?: boolean
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["deployCodeCoverage"]>

export type DeployCodeCoverageSelectScalar = {
  id?: boolean
  className?: boolean
  numLocations?: boolean
  numLocationsNotCovered?: boolean
  deploymentId?: boolean
}

export type DeployCodeCoverageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "className" | "numLocations" | "numLocationsNotCovered" | "deploymentId", ExtArgs["result"]["deployCodeCoverage"]>
export type DeployCodeCoverageInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}
export type DeployCodeCoverageIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}
export type DeployCodeCoverageIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Deployment?: boolean | Prisma.DeploymentDefaultArgs<ExtArgs>
}

export type $DeployCodeCoveragePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DeployCodeCoverage"
  objects: {
    Deployment: Prisma.$DeploymentPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    className: string
    numLocations: number
    numLocationsNotCovered: number
    deploymentId: string
  }, ExtArgs["result"]["deployCodeCoverage"]>
  composites: {}
}

export type DeployCodeCoverageGetPayload<S extends boolean | null | undefined | DeployCodeCoverageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DeployCodeCoveragePayload, S>

export type DeployCodeCoverageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DeployCodeCoverageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DeployCodeCoverageCountAggregateInputType | true
  }

export interface DeployCodeCoverageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DeployCodeCoverage'], meta: { name: 'DeployCodeCoverage' } }
  /**
   * Find zero or one DeployCodeCoverage that matches the filter.
   * @param {DeployCodeCoverageFindUniqueArgs} args - Arguments to find a DeployCodeCoverage
   * @example
   * // Get one DeployCodeCoverage
   * const deployCodeCoverage = await prisma.deployCodeCoverage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DeployCodeCoverageFindUniqueArgs>(args: Prisma.SelectSubset<T, DeployCodeCoverageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DeployCodeCoverageClient<runtime.Types.Result.GetResult<Prisma.$DeployCodeCoveragePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DeployCodeCoverage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DeployCodeCoverageFindUniqueOrThrowArgs} args - Arguments to find a DeployCodeCoverage
   * @example
   * // Get one DeployCodeCoverage
   * const deployCodeCoverage = await prisma.deployCodeCoverage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DeployCodeCoverageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DeployCodeCoverageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DeployCodeCoverageClient<runtime.Types.Result.GetResult<Prisma.$DeployCodeCoveragePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DeployCodeCoverage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployCodeCoverageFindFirstArgs} args - Arguments to find a DeployCodeCoverage
   * @example
   * // Get one DeployCodeCoverage
   * const deployCodeCoverage = await prisma.deployCodeCoverage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DeployCodeCoverageFindFirstArgs>(args?: Prisma.SelectSubset<T, DeployCodeCoverageFindFirstArgs<ExtArgs>>): Prisma.Prisma__DeployCodeCoverageClient<runtime.Types.Result.GetResult<Prisma.$DeployCodeCoveragePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DeployCodeCoverage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployCodeCoverageFindFirstOrThrowArgs} args - Arguments to find a DeployCodeCoverage
   * @example
   * // Get one DeployCodeCoverage
   * const deployCodeCoverage = await prisma.deployCodeCoverage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DeployCodeCoverageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DeployCodeCoverageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DeployCodeCoverageClient<runtime.Types.Result.GetResult<Prisma.$DeployCodeCoveragePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DeployCodeCoverages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployCodeCoverageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DeployCodeCoverages
   * const deployCodeCoverages = await prisma.deployCodeCoverage.findMany()
   * 
   * // Get first 10 DeployCodeCoverages
   * const deployCodeCoverages = await prisma.deployCodeCoverage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const deployCodeCoverageWithIdOnly = await prisma.deployCodeCoverage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DeployCodeCoverageFindManyArgs>(args?: Prisma.SelectSubset<T, DeployCodeCoverageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DeployCodeCoveragePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DeployCodeCoverage.
   * @param {DeployCodeCoverageCreateArgs} args - Arguments to create a DeployCodeCoverage.
   * @example
   * // Create one DeployCodeCoverage
   * const DeployCodeCoverage = await prisma.deployCodeCoverage.create({
   *   data: {
   *     // ... data to create a DeployCodeCoverage
   *   }
   * })
   * 
   */
  create<T extends DeployCodeCoverageCreateArgs>(args: Prisma.SelectSubset<T, DeployCodeCoverageCreateArgs<ExtArgs>>): Prisma.Prisma__DeployCodeCoverageClient<runtime.Types.Result.GetResult<Prisma.$DeployCodeCoveragePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DeployCodeCoverages.
   * @param {DeployCodeCoverageCreateManyArgs} args - Arguments to create many DeployCodeCoverages.
   * @example
   * // Create many DeployCodeCoverages
   * const deployCodeCoverage = await prisma.deployCodeCoverage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DeployCodeCoverageCreateManyArgs>(args?: Prisma.SelectSubset<T, DeployCodeCoverageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DeployCodeCoverages and returns the data saved in the database.
   * @param {DeployCodeCoverageCreateManyAndReturnArgs} args - Arguments to create many DeployCodeCoverages.
   * @example
   * // Create many DeployCodeCoverages
   * const deployCodeCoverage = await prisma.deployCodeCoverage.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DeployCodeCoverages and only return the `id`
   * const deployCodeCoverageWithIdOnly = await prisma.deployCodeCoverage.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DeployCodeCoverageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DeployCodeCoverageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DeployCodeCoveragePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DeployCodeCoverage.
   * @param {DeployCodeCoverageDeleteArgs} args - Arguments to delete one DeployCodeCoverage.
   * @example
   * // Delete one DeployCodeCoverage
   * const DeployCodeCoverage = await prisma.deployCodeCoverage.delete({
   *   where: {
   *     // ... filter to delete one DeployCodeCoverage
   *   }
   * })
   * 
   */
  delete<T extends DeployCodeCoverageDeleteArgs>(args: Prisma.SelectSubset<T, DeployCodeCoverageDeleteArgs<ExtArgs>>): Prisma.Prisma__DeployCodeCoverageClient<runtime.Types.Result.GetResult<Prisma.$DeployCodeCoveragePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DeployCodeCoverage.
   * @param {DeployCodeCoverageUpdateArgs} args - Arguments to update one DeployCodeCoverage.
   * @example
   * // Update one DeployCodeCoverage
   * const deployCodeCoverage = await prisma.deployCodeCoverage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DeployCodeCoverageUpdateArgs>(args: Prisma.SelectSubset<T, DeployCodeCoverageUpdateArgs<ExtArgs>>): Prisma.Prisma__DeployCodeCoverageClient<runtime.Types.Result.GetResult<Prisma.$DeployCodeCoveragePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DeployCodeCoverages.
   * @param {DeployCodeCoverageDeleteManyArgs} args - Arguments to filter DeployCodeCoverages to delete.
   * @example
   * // Delete a few DeployCodeCoverages
   * const { count } = await prisma.deployCodeCoverage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DeployCodeCoverageDeleteManyArgs>(args?: Prisma.SelectSubset<T, DeployCodeCoverageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DeployCodeCoverages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployCodeCoverageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DeployCodeCoverages
   * const deployCodeCoverage = await prisma.deployCodeCoverage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DeployCodeCoverageUpdateManyArgs>(args: Prisma.SelectSubset<T, DeployCodeCoverageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DeployCodeCoverages and returns the data updated in the database.
   * @param {DeployCodeCoverageUpdateManyAndReturnArgs} args - Arguments to update many DeployCodeCoverages.
   * @example
   * // Update many DeployCodeCoverages
   * const deployCodeCoverage = await prisma.deployCodeCoverage.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DeployCodeCoverages and only return the `id`
   * const deployCodeCoverageWithIdOnly = await prisma.deployCodeCoverage.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DeployCodeCoverageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DeployCodeCoverageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DeployCodeCoveragePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DeployCodeCoverage.
   * @param {DeployCodeCoverageUpsertArgs} args - Arguments to update or create a DeployCodeCoverage.
   * @example
   * // Update or create a DeployCodeCoverage
   * const deployCodeCoverage = await prisma.deployCodeCoverage.upsert({
   *   create: {
   *     // ... data to create a DeployCodeCoverage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DeployCodeCoverage we want to update
   *   }
   * })
   */
  upsert<T extends DeployCodeCoverageUpsertArgs>(args: Prisma.SelectSubset<T, DeployCodeCoverageUpsertArgs<ExtArgs>>): Prisma.Prisma__DeployCodeCoverageClient<runtime.Types.Result.GetResult<Prisma.$DeployCodeCoveragePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DeployCodeCoverages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployCodeCoverageCountArgs} args - Arguments to filter DeployCodeCoverages to count.
   * @example
   * // Count the number of DeployCodeCoverages
   * const count = await prisma.deployCodeCoverage.count({
   *   where: {
   *     // ... the filter for the DeployCodeCoverages we want to count
   *   }
   * })
  **/
  count<T extends DeployCodeCoverageCountArgs>(
    args?: Prisma.Subset<T, DeployCodeCoverageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DeployCodeCoverageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DeployCodeCoverage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployCodeCoverageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DeployCodeCoverageAggregateArgs>(args: Prisma.Subset<T, DeployCodeCoverageAggregateArgs>): Prisma.PrismaPromise<GetDeployCodeCoverageAggregateType<T>>

  /**
   * Group by DeployCodeCoverage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeployCodeCoverageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DeployCodeCoverageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DeployCodeCoverageGroupByArgs['orderBy'] }
      : { orderBy?: DeployCodeCoverageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DeployCodeCoverageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDeployCodeCoverageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DeployCodeCoverage model
 */
readonly fields: DeployCodeCoverageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DeployCodeCoverage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DeployCodeCoverageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Deployment<T extends Prisma.DeploymentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DeploymentDefaultArgs<ExtArgs>>): Prisma.Prisma__DeploymentClient<runtime.Types.Result.GetResult<Prisma.$DeploymentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DeployCodeCoverage model
 */
export interface DeployCodeCoverageFieldRefs {
  readonly id: Prisma.FieldRef<"DeployCodeCoverage", 'String'>
  readonly className: Prisma.FieldRef<"DeployCodeCoverage", 'String'>
  readonly numLocations: Prisma.FieldRef<"DeployCodeCoverage", 'Int'>
  readonly numLocationsNotCovered: Prisma.FieldRef<"DeployCodeCoverage", 'Int'>
  readonly deploymentId: Prisma.FieldRef<"DeployCodeCoverage", 'String'>
}
    

// Custom InputTypes
/**
 * DeployCodeCoverage findUnique
 */
export type DeployCodeCoverageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployCodeCoverage
   */
  select?: Prisma.DeployCodeCoverageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployCodeCoverage
   */
  omit?: Prisma.DeployCodeCoverageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployCodeCoverageInclude<ExtArgs> | null
  /**
   * Filter, which DeployCodeCoverage to fetch.
   */
  where: Prisma.DeployCodeCoverageWhereUniqueInput
}

/**
 * DeployCodeCoverage findUniqueOrThrow
 */
export type DeployCodeCoverageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployCodeCoverage
   */
  select?: Prisma.DeployCodeCoverageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployCodeCoverage
   */
  omit?: Prisma.DeployCodeCoverageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployCodeCoverageInclude<ExtArgs> | null
  /**
   * Filter, which DeployCodeCoverage to fetch.
   */
  where: Prisma.DeployCodeCoverageWhereUniqueInput
}

/**
 * DeployCodeCoverage findFirst
 */
export type DeployCodeCoverageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployCodeCoverage
   */
  select?: Prisma.DeployCodeCoverageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployCodeCoverage
   */
  omit?: Prisma.DeployCodeCoverageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployCodeCoverageInclude<ExtArgs> | null
  /**
   * Filter, which DeployCodeCoverage to fetch.
   */
  where?: Prisma.DeployCodeCoverageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DeployCodeCoverages to fetch.
   */
  orderBy?: Prisma.DeployCodeCoverageOrderByWithRelationInput | Prisma.DeployCodeCoverageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DeployCodeCoverages.
   */
  cursor?: Prisma.DeployCodeCoverageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DeployCodeCoverages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DeployCodeCoverages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DeployCodeCoverages.
   */
  distinct?: Prisma.DeployCodeCoverageScalarFieldEnum | Prisma.DeployCodeCoverageScalarFieldEnum[]
}

/**
 * DeployCodeCoverage findFirstOrThrow
 */
export type DeployCodeCoverageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployCodeCoverage
   */
  select?: Prisma.DeployCodeCoverageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployCodeCoverage
   */
  omit?: Prisma.DeployCodeCoverageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployCodeCoverageInclude<ExtArgs> | null
  /**
   * Filter, which DeployCodeCoverage to fetch.
   */
  where?: Prisma.DeployCodeCoverageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DeployCodeCoverages to fetch.
   */
  orderBy?: Prisma.DeployCodeCoverageOrderByWithRelationInput | Prisma.DeployCodeCoverageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DeployCodeCoverages.
   */
  cursor?: Prisma.DeployCodeCoverageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DeployCodeCoverages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DeployCodeCoverages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DeployCodeCoverages.
   */
  distinct?: Prisma.DeployCodeCoverageScalarFieldEnum | Prisma.DeployCodeCoverageScalarFieldEnum[]
}

/**
 * DeployCodeCoverage findMany
 */
export type DeployCodeCoverageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployCodeCoverage
   */
  select?: Prisma.DeployCodeCoverageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployCodeCoverage
   */
  omit?: Prisma.DeployCodeCoverageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployCodeCoverageInclude<ExtArgs> | null
  /**
   * Filter, which DeployCodeCoverages to fetch.
   */
  where?: Prisma.DeployCodeCoverageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DeployCodeCoverages to fetch.
   */
  orderBy?: Prisma.DeployCodeCoverageOrderByWithRelationInput | Prisma.DeployCodeCoverageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DeployCodeCoverages.
   */
  cursor?: Prisma.DeployCodeCoverageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DeployCodeCoverages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DeployCodeCoverages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DeployCodeCoverages.
   */
  distinct?: Prisma.DeployCodeCoverageScalarFieldEnum | Prisma.DeployCodeCoverageScalarFieldEnum[]
}

/**
 * DeployCodeCoverage create
 */
export type DeployCodeCoverageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployCodeCoverage
   */
  select?: Prisma.DeployCodeCoverageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployCodeCoverage
   */
  omit?: Prisma.DeployCodeCoverageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployCodeCoverageInclude<ExtArgs> | null
  /**
   * The data needed to create a DeployCodeCoverage.
   */
  data: Prisma.XOR<Prisma.DeployCodeCoverageCreateInput, Prisma.DeployCodeCoverageUncheckedCreateInput>
}

/**
 * DeployCodeCoverage createMany
 */
export type DeployCodeCoverageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DeployCodeCoverages.
   */
  data: Prisma.DeployCodeCoverageCreateManyInput | Prisma.DeployCodeCoverageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DeployCodeCoverage createManyAndReturn
 */
export type DeployCodeCoverageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployCodeCoverage
   */
  select?: Prisma.DeployCodeCoverageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DeployCodeCoverage
   */
  omit?: Prisma.DeployCodeCoverageOmit<ExtArgs> | null
  /**
   * The data used to create many DeployCodeCoverages.
   */
  data: Prisma.DeployCodeCoverageCreateManyInput | Prisma.DeployCodeCoverageCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployCodeCoverageIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DeployCodeCoverage update
 */
export type DeployCodeCoverageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployCodeCoverage
   */
  select?: Prisma.DeployCodeCoverageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployCodeCoverage
   */
  omit?: Prisma.DeployCodeCoverageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployCodeCoverageInclude<ExtArgs> | null
  /**
   * The data needed to update a DeployCodeCoverage.
   */
  data: Prisma.XOR<Prisma.DeployCodeCoverageUpdateInput, Prisma.DeployCodeCoverageUncheckedUpdateInput>
  /**
   * Choose, which DeployCodeCoverage to update.
   */
  where: Prisma.DeployCodeCoverageWhereUniqueInput
}

/**
 * DeployCodeCoverage updateMany
 */
export type DeployCodeCoverageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DeployCodeCoverages.
   */
  data: Prisma.XOR<Prisma.DeployCodeCoverageUpdateManyMutationInput, Prisma.DeployCodeCoverageUncheckedUpdateManyInput>
  /**
   * Filter which DeployCodeCoverages to update
   */
  where?: Prisma.DeployCodeCoverageWhereInput
  /**
   * Limit how many DeployCodeCoverages to update.
   */
  limit?: number
}

/**
 * DeployCodeCoverage updateManyAndReturn
 */
export type DeployCodeCoverageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployCodeCoverage
   */
  select?: Prisma.DeployCodeCoverageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DeployCodeCoverage
   */
  omit?: Prisma.DeployCodeCoverageOmit<ExtArgs> | null
  /**
   * The data used to update DeployCodeCoverages.
   */
  data: Prisma.XOR<Prisma.DeployCodeCoverageUpdateManyMutationInput, Prisma.DeployCodeCoverageUncheckedUpdateManyInput>
  /**
   * Filter which DeployCodeCoverages to update
   */
  where?: Prisma.DeployCodeCoverageWhereInput
  /**
   * Limit how many DeployCodeCoverages to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployCodeCoverageIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DeployCodeCoverage upsert
 */
export type DeployCodeCoverageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployCodeCoverage
   */
  select?: Prisma.DeployCodeCoverageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployCodeCoverage
   */
  omit?: Prisma.DeployCodeCoverageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployCodeCoverageInclude<ExtArgs> | null
  /**
   * The filter to search for the DeployCodeCoverage to update in case it exists.
   */
  where: Prisma.DeployCodeCoverageWhereUniqueInput
  /**
   * In case the DeployCodeCoverage found by the `where` argument doesn't exist, create a new DeployCodeCoverage with this data.
   */
  create: Prisma.XOR<Prisma.DeployCodeCoverageCreateInput, Prisma.DeployCodeCoverageUncheckedCreateInput>
  /**
   * In case the DeployCodeCoverage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DeployCodeCoverageUpdateInput, Prisma.DeployCodeCoverageUncheckedUpdateInput>
}

/**
 * DeployCodeCoverage delete
 */
export type DeployCodeCoverageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployCodeCoverage
   */
  select?: Prisma.DeployCodeCoverageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployCodeCoverage
   */
  omit?: Prisma.DeployCodeCoverageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployCodeCoverageInclude<ExtArgs> | null
  /**
   * Filter which DeployCodeCoverage to delete.
   */
  where: Prisma.DeployCodeCoverageWhereUniqueInput
}

/**
 * DeployCodeCoverage deleteMany
 */
export type DeployCodeCoverageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DeployCodeCoverages to delete
   */
  where?: Prisma.DeployCodeCoverageWhereInput
  /**
   * Limit how many DeployCodeCoverages to delete.
   */
  limit?: number
}

/**
 * DeployCodeCoverage without action
 */
export type DeployCodeCoverageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeployCodeCoverage
   */
  select?: Prisma.DeployCodeCoverageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeployCodeCoverage
   */
  omit?: Prisma.DeployCodeCoverageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeployCodeCoverageInclude<ExtArgs> | null
}
